/**
 * Thin abstract base class on top of Drizzle (mysql-core). Implements the same contract
 * (method vocabulary, design decisions) as `SQLiteModel` in `sqlite_model.ts` and
 * `PgModel` in `pg_model.ts`, ported in parallel for mysql-core (parallel per-dialect
 * implementations, not unified generics).
 *
 * ## db type design: promoting TQueryResult/TPreparedQueryHKT to class type parameters
 * For the same reason as `PgModel`, `MySqlDatabase<TQueryResult extends MySqlQueryResultHKT,
 * TPreparedQueryHKT extends PreparedQueryHKTBase, TFullSchema, TSchema>` cannot be fixed
 * to `unknown` (both `MySqlQueryResultHKT` and `PreparedQueryHKTBase` are constrained
 * generics following the higher-kinded-type (HKT) pattern, carrying things like
 * `$brand`). Since mysql2 (`MySql2Database`) extends `MySqlDatabase` with
 * `MySql2QueryResultHKT`/`MySql2PreparedQueryHKT`, and PlanetScale (`PlanetScaleDatabase`)
 * extends it with the different `PlanetscaleQueryResultHKT`/`PlanetScalePreparedQueryHKT`
 * (confirmed in `node_modules/drizzle-orm/{mysql2,planetscale-serverless}/driver.d.ts`),
 * both are promoted to the class's type parameters.
 *
 * ## MySQL-specific design decisions
 *
 * ### Working around the lack of RETURNING support (create/update/upsert/delete)
 * MySQL doesn't support UPDATE/DELETE/INSERT ... RETURNING (confirmed that mysql-core's
 * `insert()`/`update()`/`delete()` expose no `.returning()` method in
 * `node_modules/drizzle-orm/mysql-core/query-builders/{insert,update,delete}.d.ts`.
 * `insert()` does have a separate `$returningId()` API, but it only returns the
 * generated AUTO_INCREMENT primary key, not arbitrary columns). So the contract "the DB
 * returns the row it actually committed" is implemented as **an approximation: re-SELECT
 * by the already-known primary key after the write**:
 * - `create`/`createMany`: `id` is pre-generated by the application-side `IdGenerator`
 *   before the write, so it's already known. `retrieve` it by that `id` after writing.
 * - `update`/`delete`: the `pk` argument is already known. `retrieve` it by that `pk`
 *   after writing (`delete` retrieves it before deleting).
 * - `upsert`: `retrieve`s by `input`'s `id` (the unique key used for conflict detection,
 *   same assumption as `create`) after writing.
 *
 * **This approximation is non-atomic** (another query can interleave between the write
 * and the re-SELECT; under concurrent updates to the same row, the value returned may
 * reflect a subsequent state rather than "the value actually written"). SQLite/Postgres'
 * RETURNING performs the write and the read atomically as a single statement within the
 * same transaction, so the MySQL version offers a weaker guarantee here. Using it inside
 * a transaction (`with(tx)`) mitigates this within that transaction's isolation level,
 * but note it's still not fully equivalent.
 *
 * ### Getting the affected-row count for updateWhere (the `rowsAffectedFrom` hook)
 * The shape of the execution result object for `update()`/`delete()` differs by driver
 * (mysql2 returns a `[ResultSetHeader, FieldPacket[]]` tuple with `affectedRows`,
 * confirmed as `MySqlRawQueryResult` in `node_modules/drizzle-orm/mysql2/session.d.ts`;
 * PlanetScale uses the different `ExecutedQuery` shape). The default implementation
 * reads the mysql2 shape via a type guard, and throws with a clear message
 * ("override rowsAffectedFrom in a subclass") for unknown shapes, rather than silently
 * defaulting to `0`.
 *
 * **`affectedRows` counts "rows whose value actually changed", not "rows matched by
 * WHERE"** (for UPDATE on a mysql2 default connection, i.e. one that hasn't requested
 * the `CLIENT_FOUND_ROWS` flag). If `updateWhere` is used for optimistic locking like
 * `WHERE status = 'unused'` and `patch` can end up identical to the existing value, a
 * row that both exists and matches the condition can be miscounted as 0 rows ("matched
 * but unchanged"). Enable `CLIENT_FOUND_ROWS` on the connection when using it for this
 * purpose. `updateLocked` always increments `lockVersion` to `expectedVersion + 1`, so
 * its value always changes and it's unaffected by this issue.
 *
 * ### upsert (`onDuplicateKeyUpdate`)
 * mysql-core has no `onConflictDoUpdate`; only `onDuplicateKeyUpdate({ set })` exists
 * (confirmed as `MySqlInsertOnDuplicateKeyUpdateConfig` in
 * `node_modules/drizzle-orm/mysql-core/query-builders/insert.d.ts`). SQLite/Postgres'
 * `onConflictDoUpdate` lets you specify a `target` (the UNIQUE constraint column
 * determining the conflict), but MySQL's `ON DUPLICATE KEY UPDATE` can't target a
 * specific column — it applies uniformly "when the row conflicts with any UNIQUE
 * constraint present (including the primary key)". So `MySqlUpsertConflict` has **no
 * `target`** (a contract difference from SQLite/Postgres' `SQLiteUpsertConflict`/
 * `PgUpsertConflict`).
 *
 * Drizzle is already an excellent ORM layer, so we don't wrap it deeply: subclasses are
 * free to write `this.db.select()...` directly. What the base class absorbs is limited
 * to the boilerplate repeated across every model (id generation, automatic
 * `createdAt`/`updatedAt` management, cursor pagination, optimistic-lock UPDATE,
 * transaction binding), same policy as `SQLiteModel`/`PgModel`.
 *
 * Deliberately not provided:
 * - Lifecycle callbacks (before/after hooks): hard-to-trace magic
 * - Validation: that's the Form layer's responsibility; the model stays a thin DB layer
 *   that trusts already-normalized input
 */
import {
	and,
	asc,
	count as countRows,
	desc,
	eq,
	getTableColumns,
	getTableName,
	gt,
	inArray,
	lt,
	sql,
	type GetColumnData,
	type SQL,
} from "drizzle-orm";
import type {
	MySqlColumn,
	MySqlDatabase,
	MySqlQueryResultHKT,
	MySqlTable,
	PreparedQueryHKTBase,
} from "drizzle-orm/mysql-core";
import { SnowflakeIdGenerator } from "../support/id_generator.js";
import type { IdGenerator } from "../support/id_generator.js";
import { StaleRecordError } from "./stale_record_error.js";

/** Column names that `MySqlModel` manages automatically, when the table actually has them. */
type AutoManagedKey = "id" | "createdAt" | "updatedAt";

/**
 * Default upper bound on the number of values accepted by `listIn`/`groupedIn`/
 * `retrieveMany` (methods that pass a set of values to an `IN` clause). Set to 1000,
 * large enough not to break existing call sites (same default as `SQLiteModel`/
 * `PgModel`; can be overridden via `MySqlModel`'s third constructor argument).
 */
const DEFAULT_MAX_IN_VALUES = 1000;

/**
 * Input type for `create`/`createMany`. Makes the `id`/`createdAt`/`updatedAt` columns
 * optional when the table has them (since the base class fills them in automatically).
 * For tables that don't have them, this transform is a no-op and other required columns
 * stay required (same contract as `SQLiteModel`'s `Creatable`).
 */
type Creatable<TTable extends MySqlTable> = Omit<TTable["$inferInsert"], AutoManagedKey> &
	Partial<Pick<TTable["$inferInsert"], Extract<keyof TTable["$inferInsert"], AutoManagedKey>>>;

/**
 * Derives a MySQL table's row type from `$inferSelect` (specific to `MySqlModel`; the
 * SQLite counterpart is `SQLiteModelRecord`, the Postgres counterpart is `PgModelRecord`).
 */
export type MySqlModelRecord<TTable extends MySqlTable> = TTable["$inferSelect"];

/**
 * Arguments for `MySqlModel#paginate`. The cursor is the primary key value of the last
 * row of the previous page, in the order given by `direction`. Defaults to `"asc"` when
 * `direction` is omitted (for backward compatibility).
 */
export type MySqlPaginateOptions<TPk extends MySqlColumn> = {
	cursor?: GetColumnData<TPk, "raw">;
	limit: number;
	direction?: "asc" | "desc";
	/** Optional filter condition, ANDed with the cursor condition. For search/scoped listings. */
	where?: SQL;
};

/** Return value of `MySqlModel#paginate`. */
export type MySqlPaginateResult<TTable extends MySqlTable, TPk extends MySqlColumn> = {
	rows: MySqlModelRecord<TTable>[];
	nextCursor: GetColumnData<TPk, "raw"> | null;
	hasMore: boolean;
};

/** Arguments for `MySqlModel#listPage`. */
export type MySqlListPageOptions = {
	where?: SQL;
	/** Sort columns, applied in array order. Defaults to primary key ascending when omitted or empty. */
	orderBy?: { column: MySqlColumn; direction: "asc" | "desc" }[];
	limit: number;
	offset?: number;
};

/**
 * Conflict resolution for `MySqlModel#upsert`. MySQL's `ON DUPLICATE KEY UPDATE` can't
 * target a specific column (see module JSDoc "upsert"), so this has no equivalent to
 * SQLite/Postgres' `target` (only `set`).
 */
export type MySqlUpsertConflict<TTable extends MySqlTable> = {
	set: Partial<TTable["$inferInsert"]>;
};

/** Shape of the mysql2 driver's `update`/`delete` execution result (`[ResultSetHeader, FieldPacket[]]`). */
type MySql2StyleResult = readonly [{ affectedRows: number }, ...unknown[]];

/** Whether `value` is a mysql2-shaped execution result (one the default `rowsAffectedFrom` implementation can read). */
const isMySql2StyleResult = (value: unknown): value is MySql2StyleResult =>
	Array.isArray(value) &&
	value.length > 0 &&
	typeof value[0] === "object" &&
	value[0] !== null &&
	"affectedRows" in value[0] &&
	typeof value[0].affectedRows === "number";

/**
 * Extracts `id` from the `values` filled in by `withAutoFields` (used by `create`/
 * `upsert` for the post-write re-SELECT). Since `values`' type `TTable["$inferInsert"]`
 * can't statically track a table's dynamic column composition (same reason as
 * `withAutoFields`), `as` is used only here.
 */
const idOf = <TPk extends MySqlColumn>(
	values: Record<string, unknown>,
): GetColumnData<TPk, "raw"> => values.id as GetColumnData<TPk, "raw">;

export abstract class MySqlModel<
	TTable extends MySqlTable,
	TPk extends MySqlColumn,
	TQueryResult extends MySqlQueryResultHKT,
	TPreparedQueryHKT extends PreparedQueryHKTBase,
	TSchema extends Record<string, unknown> = Record<string, never>,
> {
	constructor(
		protected readonly db: MySqlDatabase<TQueryResult, TPreparedQueryHKT, TSchema>,
		private readonly idGenerator: IdGenerator = new SnowflakeIdGenerator(),
		private readonly maxInValues: number = DEFAULT_MAX_IN_VALUES,
	) {}

	/** Target table. Declared by the subclass (e.g. `protected get table() { return items; }`). */
	protected abstract get table(): TTable;

	/** Primary key column. Declared by the subclass (e.g. `protected get primaryKey() { return items.id; }`). */
	protected abstract get primaryKey(): TPk;

	/**
	 * Hook that reads the number of rows actually changed/deleted from the execution
	 * result of `update()`/`updateWhere()`/`delete()`. The default implementation reads
	 * the mysql2 execution result shape (`[ResultSetHeader, FieldPacket[]]`; see module
	 * JSDoc "Getting the affected-row count for updateWhere"). Subclasses using a
	 * non-mysql2 driver (PlanetScale, etc.) should override this method.
	 *
	 * Note: on a mysql2 default connection, UPDATE's `affectedRows` counts "rows whose
	 * value actually changed", not "rows matched by WHERE" (see module JSDoc "Getting
	 * the affected-row count for updateWhere").
	 */
	protected rowsAffectedFrom(result: unknown): number {
		if (isMySql2StyleResult(result)) return result[0].affectedRows;
		throw new Error(
			"MySqlModel#rowsAffectedFrom: unknown execution result shape. When using a driver " +
				"other than mysql2 (e.g. PlanetScale), override rowsAffectedFrom in a subclass with " +
				"an implementation that reads the row count from that driver's execution result.",
		);
	}

	/** Fetches a single row by primary key. Returns `undefined` if it doesn't exist. */
	async retrieve(pk: GetColumnData<TPk, "raw">): Promise<MySqlModelRecord<TTable> | undefined> {
		const [row] = await this.db.select().from(this.table).where(eq(this.primaryKey, pk)).limit(1);
		return row;
	}

	/**
	 * Fetches a single row by primary key while acquiring a row lock via
	 * `SELECT ... FOR UPDATE` (pessimistic locking). Signature and return type match
	 * `retrieve`.
	 *
	 * **A row lock only has meaning inside a transaction.** Call this through a
	 * transaction-bound instance obtained via `with(tx)`. Called outside a transaction
	 * (autocommit), the lock is released as soon as the statement finishes executing,
	 * so it can't prevent another transaction from interleaving before the following
	 * read/update.
	 *
	 * ```ts
	 * await db.transaction(async (tx) => {
	 *   const item = await items.with(tx).retrieveForUpdate(id);
	 *   if (!item) throw new Error("not found");
	 *   await items.with(tx).update(id, { count: item.count + 1 });
	 * });
	 * ```
	 *
	 * `SQLiteModel` has no equivalent method: SQLite has no row lock (`FOR UPDATE`);
	 * writes are locked at the database level instead. This is a deliberate case where
	 * the method vocabulary is asymmetric across dialects.
	 */
	async retrieveForUpdate(
		pk: GetColumnData<TPk, "raw">,
	): Promise<MySqlModelRecord<TTable> | undefined> {
		const [row] = await this.db
			.select()
			.from(this.table)
			.where(eq(this.primaryKey, pk))
			.limit(1)
			.for("update");
		return row;
	}

	/**
	 * Fetches a single row by an arbitrary condition. Returns `undefined` if none match;
	 * if multiple rows match, only the first is returned. `where` is typed as
	 * `SQL | undefined` (the same type Drizzle's `.where()` accepts) so that a value
	 * built dynamically from a condition array (e.g. via `and(...)`) can be passed
	 * straight through. The parameter itself is required (not optional) to encourage
	 * callers to be explicit about their condition.
	 */
	async retrieveBy(where: SQL | undefined): Promise<MySqlModelRecord<TTable> | undefined> {
		const [row] = await this.db.select().from(this.table).where(where).limit(1);
		return row;
	}

	/**
	 * Returns every row matching `where` (all rows if `where` is omitted). There is no
	 * row limit, so on large tables this can load an unbounded result set into memory.
	 * Use `paginate` when the result set may be large.
	 */
	async list(where?: SQL): Promise<MySqlModelRecord<TTable>[]> {
		return this.db.select().from(this.table).where(where);
	}

	/** Whether at least one row matches `where`. */
	async exists(where?: SQL): Promise<boolean> {
		const [row] = await this.db
			.select({ found: sql<number>`1` })
			.from(this.table)
			.where(where)
			.limit(1);
		return row !== undefined;
	}

	/** Number of rows matching `where`. */
	async count(where?: SQL): Promise<number> {
		const [row] = await this.db.select({ value: countRows() }).from(this.table).where(where);
		return row?.value ?? 0;
	}

	/** Returns only the values of the given column as an array (all rows if `where` is omitted). */
	async pluck<TColumn extends MySqlColumn>(
		column: TColumn,
		where?: SQL,
	): Promise<GetColumnData<TColumn>[]> {
		const rows = await this.db.select({ value: column }).from(this.table).where(where);
		return rows.map((row) => row.value);
	}

	/**
	 * Returns every row whose `column` value matches one of `values`
	 * (`WHERE column IN (values)`; same contract as `SQLiteModel#listIn`/
	 * `PgModel#listIn`). A vocabulary for bulk-fetching by a set of parent IDs/FKs,
	 * avoiding an N+1 pattern of calling `retrieve`/`list` in a loop (also the basis of
	 * `groupedIn`/`retrieveMany`). If `values` is an empty array, no query is issued and
	 * `[]` is returned (an empty `IN ()` is invalid SQL syntax). If `values.length`
	 * exceeds the third constructor argument `maxInValues` (default `1000`), no query
	 * is issued and this throws instead (a guard against unbounded `IN` clause
	 * expansion; use `paginate`'s `where` for large-scale filtering).
	 */
	async listIn<TColumn extends MySqlColumn>(
		column: TColumn,
		values: readonly GetColumnData<TColumn, "raw">[],
	): Promise<MySqlModelRecord<TTable>[]> {
		if (values.length === 0) return [];
		this.assertWithinMaxInValues(values.length);
		return this.db.select().from(this.table).where(inArray(column, values));
	}

	/**
	 * Performs the same fetch as `listIn` but returns a `Map` grouped by the `column`
	 * value (same contract as `SQLiteModel#groupedIn`/`PgModel#groupedIn`). A vocabulary
	 * for bulk-loading a "has many" relation without an N+1 pattern of calling `list`
	 * in a loop (`groupedIn(fkColumn, parentIds)` yields `parentId -> childRows[]`). A
	 * column value with no matching rows in `values` simply has no key in the map.
	 * Returns an empty map (no query issued) if `values` is empty.
	 *
	 * Since the grouping key is the value of a dynamic column (`column`), TypeScript
	 * cannot statically track it as a property name of `MySqlModelRecord<TTable>`, so
	 * it's read using the same technique as `paginate`'s `__cursor` (aliasing `column`
	 * as `__group` in the `select` and destructuring it back off). The
	 * `values.length` upper-bound guard is the same as `listIn` (throws once
	 * `maxInValues` is exceeded).
	 */
	async groupedIn<TColumn extends MySqlColumn>(
		column: TColumn,
		values: readonly GetColumnData<TColumn, "raw">[],
	): Promise<Map<GetColumnData<TColumn, "raw">, MySqlModelRecord<TTable>[]>> {
		const grouped = new Map<GetColumnData<TColumn, "raw">, MySqlModelRecord<TTable>[]>();
		if (values.length === 0) return grouped;
		this.assertWithinMaxInValues(values.length);

		const fetched = await this.db
			.select({ ...getTableColumns(this.table), __group: column })
			.from(this.table)
			.where(inArray(column, values));

		for (const { __group, ...record } of fetched) {
			/** The structural reason `record` matches `MySqlModelRecord<TTable>` is the same as in `paginate`. */
			const row = record as MySqlModelRecord<TTable>;
			const bucket = grouped.get(__group);
			if (bucket) bucket.push(row);
			else grouped.set(__group, [row]);
		}
		return grouped;
	}

	/**
	 * Bulk-fetches by an array of primary keys and returns `Map<primaryKeyValue, row>`
	 * (same contract as `SQLiteModel#retrieveMany`/`PgModel#retrieveMany`). A vocabulary
	 * for bulk-loading a "belongs to" relation without an N+1 pattern of calling
	 * `retrieve` in a loop (`retrieveMany(parentIds)`). A primary key that doesn't
	 * exist simply has no key in the map. Returns an empty map (no query issued) if
	 * `pks` is empty. Duplicate primary keys still result in a single query. The
	 * `pks.length` upper-bound guard is the same as `listIn` (throws once
	 * `maxInValues` is exceeded).
	 */
	async retrieveMany(
		pks: readonly GetColumnData<TPk, "raw">[],
	): Promise<Map<GetColumnData<TPk, "raw">, MySqlModelRecord<TTable>>> {
		const result = new Map<GetColumnData<TPk, "raw">, MySqlModelRecord<TTable>>();
		if (pks.length === 0) return result;
		this.assertWithinMaxInValues(pks.length);

		const fetched = await this.db
			.select({ ...getTableColumns(this.table), __pk: this.primaryKey })
			.from(this.table)
			.where(inArray(this.primaryKey, pks));

		for (const { __pk, ...record } of fetched) {
			result.set(__pk, record as MySqlModelRecord<TTable>);
		}
		return result;
	}

	/**
	 * Cursor-based pagination (same contract as `SQLiteModel#paginate`/
	 * `PgModel#paginate`; `OFFSET` is avoided).
	 *
	 * Contract: sort order is fixed to primary key order in the direction given by
	 * `direction` (default `"asc"`). `cursor` is the primary key value of the last row
	 * of the previous page; rows are returned starting after `primaryKey > cursor` for
	 * `asc`, or before `primaryKey < cursor` for `desc` (starts from the beginning if
	 * `cursor` is omitted). Fetches `limit + 1` rows; if more than `limit` rows come
	 * back, `hasMore: true` is set, `rows` returns only the first `limit` of them, and
	 * `nextCursor` is the primary key value of that last row. If the primary key is a
	 * monotonically increasing, time-ordered value (such as the Snowflake ID that is
	 * this framework's default), `asc` matches insertion order and `desc` (pass
	 * `direction: "desc"`) matches a "most recent first" listing.
	 *
	 * Passing `where` allows pagination combined with filtering (ANDed with the cursor
	 * condition).
	 */
	async paginate({
		cursor,
		limit,
		direction = "asc",
		where,
	}: MySqlPaginateOptions<TPk>): Promise<MySqlPaginateResult<TTable, TPk>> {
		const cursorCondition =
			cursor === undefined
				? undefined
				: direction === "desc"
					? lt(this.primaryKey, cursor)
					: gt(this.primaryKey, cursor);
		const condition =
			cursorCondition && where ? and(cursorCondition, where) : (cursorCondition ?? where);
		const fetched = await this.db
			.select({ ...getTableColumns(this.table), __cursor: this.primaryKey })
			.from(this.table)
			.where(condition)
			.orderBy(direction === "desc" ? desc(this.primaryKey) : asc(this.primaryKey))
			.limit(limit + 1);

		const hasMore = fetched.length > limit;
		const page = hasMore ? fetched.slice(0, limit) : fetched;
		const rows = page.map(({ __cursor, ...record }) => record);
		const last = page.at(-1);
		const nextCursor = hasMore && last !== undefined ? last.__cursor : null;

		/**
		 * `record` is `getTableColumns` (every column of the table) with only the
		 * `__cursor` alias removed, so it structurally matches `MySqlModelRecord<TTable>`,
		 * but TypeScript cannot statically track that a destructuring removal matches
		 * `$inferSelect`, so `as` is used only here (same reason as `SQLiteModel#paginate`).
		 */
		return { rows: rows as MySqlModelRecord<TTable>[], nextCursor, hasMore };
	}

	/**
	 * Offset-based pagination in arbitrary column order (same contract as
	 * `SQLiteModel#listPage`/`PgModel#listPage`). Where `paginate` is cursor-based and
	 * fixed to primary key order, `listPage` trades that for the flexibility of sorting by
	 * any column and jumping straight to a given page number — the shape a
	 * column-sortable, numbered-page admin listing needs. Prefer `paginate` for
	 * large-scale, publicly listed data: a large `offset` still requires the database to
	 * scan and discard that many rows before returning results, so `listPage` is best
	 * suited to bounded, internal-facing listings (e.g. an admin panel) rather than deep
	 * pagination over unbounded public data.
	 *
	 * `orderBy` is applied in array order; when omitted or empty, rows are sorted by
	 * primary key ascending so results stay deterministic across calls. `offset` defaults
	 * to `0`. MySQL requires `LIMIT` whenever `OFFSET` is used; `limit` is a required
	 * option here, so that constraint is always satisfied.
	 */
	async listPage(options: MySqlListPageOptions): Promise<MySqlModelRecord<TTable>[]> {
		const orderBy =
			options.orderBy && options.orderBy.length > 0
				? options.orderBy.map((entry) =>
						entry.direction === "desc" ? desc(entry.column) : asc(entry.column),
					)
				: [asc(this.primaryKey)];
		return this.db
			.select()
			.from(this.table)
			.where(options.where)
			.orderBy(...orderBy)
			.limit(options.limit)
			.offset(options.offset ?? 0);
	}

	/**
	 * Creates a single row. Automatically fills in `id`/`createdAt`/`updatedAt` (when
	 * the table has them). Since MySQL doesn't support RETURNING, the row is fetched
	 * back by re-SELECTing on the already-generated `id` after the write (see module
	 * JSDoc "Working around the lack of RETURNING support"; note this is non-atomic).
	 *
	 * Automatic `id` generation assumes the `id` column is a **string (varchar/text)**
	 * type holding the numeric string returned by the `IdGenerator` (Snowflake by
	 * default; same contract as `SQLiteModel#create`).
	 */
	async create(input: Creatable<TTable>): Promise<MySqlModelRecord<TTable>> {
		const values = this.withAutoFields(input);
		await this.db.insert(this.table).values(values);
		const row = await this.retrieve(idOf<TPk>(values));
		if (!row) {
			throw new Error("MySqlModel#create: could not find the row on the post-write re-SELECT.");
		}
		return row;
	}

	/** Bulk-creates multiple rows, generating a separate id for each. Passing an empty array is a no-op returning `[]`. */
	async createMany(inputs: Creatable<TTable>[]): Promise<MySqlModelRecord<TTable>[]> {
		if (inputs.length === 0) return [];
		const rows: MySqlModelRecord<TTable>[] = [];
		for (const input of inputs) rows.push(await this.create(input));
		return rows;
	}

	/**
	 * Updates a single row by primary key. `updatedAt` (when present on the table) is
	 * always overwritten with the current time, regardless of what the caller passes.
	 * Returns `undefined` if the target row doesn't exist. Since MySQL doesn't support
	 * RETURNING, the row is fetched back by re-SELECTing on `pk` after the write (see
	 * module JSDoc).
	 */
	async update(
		pk: GetColumnData<TPk, "raw">,
		patch: Partial<TTable["$inferInsert"]>,
	): Promise<MySqlModelRecord<TTable> | undefined> {
		await this.db
			.update(this.table)
			.set(this.withTouchedUpdatedAt(patch))
			.where(eq(this.primaryKey, pk));
		return this.retrieve(pk);
	}

	/**
	 * Bulk-updates every row matching `where` and returns the number of rows actually
	 * updated (same contract as `SQLiteModel#updateWhere`/`PgModel#updateWhere`).
	 * Provides `WHERE status = 'unused'`-style optimistic locking as a first-class
	 * method. `updatedAt` is handled the same as `update`. `where` is typed
	 * `SQL | undefined` (required, not optional) for the same reason as `retrieveBy`.
	 *
	 * The count is obtained through the `rowsAffectedFrom` hook (see module JSDoc
	 * "Getting the affected-row count for updateWhere"; a contract difference across
	 * dialects — it's read from the driver's execution result object rather than the
	 * length of a RETURNING row array as in SQLite/Postgres).
	 *
	 * Note: for optimistic-locking use cases where `patch` can end up identical to the
	 * target row's existing value (e.g. `WHERE status = 'unused'`), a mysql2 default
	 * connection can miscount as 0 rows a row that matched but whose value didn't
	 * change (see module JSDoc "Getting the affected-row count for updateWhere"). Enable
	 * `CLIENT_FOUND_ROWS` on the connection when using it for this purpose.
	 */
	async updateWhere(
		where: SQL | undefined,
		patch: Partial<TTable["$inferInsert"]>,
	): Promise<number> {
		const result = await this.db
			.update(this.table)
			.set(this.withTouchedUpdatedAt(patch))
			.where(where);
		return this.rowsAffectedFrom(result);
	}

	/**
	 * Optimistic-locking update (using a version column). A formalization
	 * of conditional updates built on `updateWhere`: pass the `lockVersion` carried over
	 * from a previous read as `expectedVersion`, and this updates
	 * `WHERE primaryKey = pk AND lockVersion = expectedVersion`, incrementing
	 * `lockVersion` to `expectedVersion + 1` on success (same contract as
	 * `SQLiteModel#updateLocked`/`PgModel#updateLocked`). `updatedAt` (when present on
	 * the table) is handled the same as `update`. Since MySQL doesn't support
	 * RETURNING, the update count is confirmed via the `rowsAffectedFrom` hook (see
	 * module JSDoc "Getting the affected-row count for updateWhere") before
	 * re-SELECTing `pk` (the same non-atomic approximation as `update`).
	 *
	 * Both "the row is gone" and "version mismatch" result in a zero-row update and
	 * can't be distinguished at the SQL level, so either case throws
	 * `StaleRecordError` (see `StaleRecordError`'s JSDoc). Even if `patch` includes
	 * `lockVersion`, it gets overwritten by the value this method manages
	 * (`expectedVersion + 1`).
	 *
	 * ```ts
	 * const item = await items.retrieve(id);
	 * if (!item) throw new Error("not found");
	 * const updated = await items.updateLocked(id, item.lockVersion, { name: "New name" });
	 * ```
	 *
	 * Note: after confirming the UPDATE succeeded, calling `retrieve(pk)` outside a
	 * transaction (autocommit) does not strictly guarantee "the value I just wrote" —
	 * between the UPDATE's commit and the re-SELECT, another transaction could write to
	 * the same row again, and the state after that subsequent write could be returned
	 * instead (see module JSDoc "Working around the lack of RETURNING support"). To
	 * strictly read back your own write, call this through a transaction bound via
	 * `with(tx)`, combined with `retrieveForUpdate` if needed.
	 */
	async updateLocked(
		pk: GetColumnData<TPk, "raw">,
		expectedVersion: number,
		patch: Partial<TTable["$inferInsert"]>,
	): Promise<MySqlModelRecord<TTable>> {
		const lockVersion = this.lockVersionColumn();
		const nextPatch = {
			...this.withTouchedUpdatedAt(patch),
			lockVersion: expectedVersion + 1,
		} as Partial<TTable["$inferInsert"]>;
		const result = await this.db
			.update(this.table)
			.set(nextPatch)
			.where(and(eq(this.primaryKey, pk), eq(lockVersion, expectedVersion)));
		if (this.rowsAffectedFrom(result) === 0) {
			throw new StaleRecordError(getTableName(this.table), pk);
		}
		const row = await this.retrieve(pk);
		if (!row) {
			throw new StaleRecordError(getTableName(this.table), pk);
		}
		return row;
	}

	/**
	 * Sets `deletedAt` to the current time (soft delete). Return value and the
	 * `updatedAt`-touching behavior follow `update`, and this delegates its
	 * implementation to `update` (same contract as `SQLiteModel#softDelete`/
	 * `PgModel#softDelete`; the "re-SELECT after write" approximation from MySQL's lack
	 * of RETURNING support is absorbed inside `update`). Returns `undefined` if the
	 * target row doesn't exist. Calling this on an already soft-deleted row is not
	 * special-cased; it simply overwrites `deletedAt` with a newer timestamp.
	 *
	 * Fetch methods like `list`/`retrieve` do not automatically exclude rows with a
	 * non-null `deletedAt` (an implicit global scope is deliberately not
	 * provided, per the "no magic" policy). Callers that want to exclude deleted rows
	 * must add `isNull(table.deletedAt)` to `where` explicitly.
	 */
	async softDelete(pk: GetColumnData<TPk, "raw">): Promise<MySqlModelRecord<TTable> | undefined> {
		this.assertDeletedAtColumn();
		return this.update(pk, { deletedAt: Date.now() } as Partial<TTable["$inferInsert"]>);
	}

	/** Resets `deletedAt` to `null` (undoes a soft delete). Contract and delegation target match `softDelete`. */
	async restore(pk: GetColumnData<TPk, "raw">): Promise<MySqlModelRecord<TTable> | undefined> {
		this.assertDeletedAtColumn();
		return this.update(pk, { deletedAt: null } as Partial<TTable["$inferInsert"]>);
	}

	/**
	 * Updates using `set` on conflict, otherwise creates a new row from `input`.
	 * `updatedAt` is handled the same as `update`. mysql-core's `onDuplicateKeyUpdate`
	 * has no `target` (see module JSDoc "upsert"). Since MySQL doesn't support
	 * RETURNING, the row is fetched back by re-SELECTing on `input`'s `id` after the
	 * write.
	 */
	async upsert(
		input: Creatable<TTable>,
		conflict: MySqlUpsertConflict<TTable>,
	): Promise<MySqlModelRecord<TTable>> {
		const values = this.withAutoFields(input);
		await this.db
			.insert(this.table)
			.values(values)
			.onDuplicateKeyUpdate({ set: this.withTouchedUpdatedAt(conflict.set) });
		const row = await this.retrieve(idOf<TPk>(values));
		if (!row) {
			throw new Error("MySqlModel#upsert: could not find the row on the post-write re-SELECT.");
		}
		return row;
	}

	/** Updates only `updatedAt` to the current time. A no-op if the table has no `updatedAt` column. */
	async touch(pk: GetColumnData<TPk, "raw">): Promise<void> {
		if (!("updatedAt" in this.table)) return;
		await this.db
			.update(this.table)
			.set(this.withTouchedUpdatedAt({}))
			.where(eq(this.primaryKey, pk));
	}

	/**
	 * Adds `delta` (default 1) to the given column, issuing SQL as
	 * `column = column + delta` (same reasoning as `SQLiteModel#increment`/
	 * `PgModel#increment` for using the raw-SQL path).
	 *
	 * The constraint that the left-hand side of `SET` (the assignment target) must be
	 * an unqualified, bare column name has been confirmed on SQLite (real database) and
	 * Postgres (PGlite), and is expected to hold the same way on MySQL. This is now
	 * covered by live tests in `test/model/mysql_model.test.ts` (relative updates
	 * across repeated calls, negative deltas, and concurrent increments), gated behind
	 * `OVEN_MYSQL_TEST_URL` and run against the `mysql:8` service container in
	 * `.github/workflows/ci.yml`; `test/test_support/mysql_ci_guard.test.ts` fails
	 * loudly instead of silently skipping if that variable is ever missing in CI. This
	 * note is kept until a follow-up change removes it once those tests have been
	 * observed green in CI. Only the left side uses `sql.identifier(column.name)` to
	 * produce a bare identifier, while the right-hand side reference stays as
	 * `${column}` (table-qualified).
	 */
	async increment(pk: GetColumnData<TPk, "raw">, column: MySqlColumn, delta = 1): Promise<void> {
		await this.db.execute(
			sql`update ${this.table} set ${sql.identifier(column.name)} = ${column} + ${delta} where ${eq(this.primaryKey, pk)}`,
		);
	}

	/** Subtracts `delta` (default 1) from the given column. The sign-flipped counterpart of `increment`. */
	async decrement(pk: GetColumnData<TPk, "raw">, column: MySqlColumn, delta = 1): Promise<void> {
		await this.increment(pk, column, -delta);
	}

	/**
	 * Deletes a single row by primary key. Returns the row (retrieved before the
	 * delete) only if it was actually deleted (since MySQL doesn't support RETURNING;
	 * see module JSDoc; a non-atomic approximation where another query can interleave
	 * between the read and the delete). Returns `undefined` both when the target row
	 * doesn't exist to begin with, and when another request already deleted the same
	 * row between the initial `retrieve` and the `delete` call (the actual delete count
	 * is confirmed via the `rowsAffectedFrom` hook; without that check, returning the
	 * snapshot unconditionally would incorrectly report success when nothing was
	 * actually deleted).
	 */
	async delete(pk: GetColumnData<TPk, "raw">): Promise<MySqlModelRecord<TTable> | undefined> {
		const row = await this.retrieve(pk);
		if (!row) return undefined;
		const result = await this.db.delete(this.table).where(eq(this.primaryKey, pk));
		if (this.rowsAffectedFrom(result) === 0) return undefined;
		return row;
	}

	/**
	 * Bulk-deletes every row matching `where` and returns the number of rows actually
	 * deleted (the DELETE counterpart of `updateWhere`, sharing the same `where`
	 * contract; same contract as `SQLiteModel#deleteWhere`/`PgModel#deleteWhere`).
	 * `where` is typed `SQL | undefined` (required, not optional) for the same reason
	 * as `retrieveBy`.
	 *
	 * **This is a hard delete** — it issues a real `DELETE` statement, unlike
	 * `softDelete`, which only sets `deletedAt`. `deleteWhere` does not auto-scope to
	 * non-deleted rows; the caller's `where` is authoritative, so callers that want to
	 * skip already soft-deleted rows must add that condition themselves (e.g.
	 * `isNull(table.deletedAt)`).
	 *
	 * Since MySQL doesn't support DELETE ... RETURNING (confirmed that mysql-core's
	 * `delete()` exposes no `.returning()` method in
	 * `node_modules/drizzle-orm/mysql-core/query-builders/delete.d.ts`), the count is
	 * obtained through the `rowsAffectedFrom` hook instead, the same way `updateWhere`
	 * does (see module JSDoc "Getting the affected-row count for updateWhere"). Unlike
	 * UPDATE's "rows whose value actually changed" nuance, DELETE's `affectedRows`
	 * straightforwardly counts rows matched by `where` and removed, so this is
	 * unaffected by the `CLIENT_FOUND_ROWS` caveat that applies to `updateWhere`.
	 */
	async deleteWhere(where: SQL | undefined): Promise<number> {
		const result = await this.db.delete(this.table).where(where);
		return this.rowsAffectedFrom(result);
	}

	/**
	 * Returns a model instance of the same type bound to a transaction. Used in
	 * cross-model orchestration (the handlers layer) like
	 * `db.transaction(async (tx) => { const txBooks = books.with(tx); ... })` (same
	 * contract as `SQLiteModel#with`/`PgModel#with`; mysql-core's `MySqlTransaction`
	 * extends `MySqlDatabase`, so it can be accepted with the same type).
	 */
	with(tx: MySqlDatabase<TQueryResult, TPreparedQueryHKT, TSchema>): this {
		/**
		 * `this.constructor` refers to the subclass at runtime (e.g. `ItemModel`), but
		 * TypeScript cannot statically track `this`'s concrete constructor type.
		 * Assuming the subclass inherits `MySqlModel`'s constructor signature
		 * `(db, idGenerator?)` unchanged (i.e. it doesn't define its own constructor),
		 * `as` is used only here to make the constructor type explicit (same reason as
		 * `SQLiteModel#with`/`PgModel#with`).
		 */
		const Ctor = this.constructor as new (
			db: MySqlDatabase<TQueryResult, TPreparedQueryHKT, TSchema>,
			idGenerator?: IdGenerator,
			maxInValues?: number,
		) => this;
		return new Ctor(tx, this.idGenerator, this.maxInValues);
	}

	/**
	 * Builds the values to insert with `id`/`createdAt`/`updatedAt` filled in (only for
	 * columns the table actually has). Presence is checked at runtime via `in` against
	 * `this.table`'s actual properties, so a column absent from the table is never
	 * mistakenly inserted. Because TypeScript cannot statically track this
	 * per-table-varying dynamic column shape, `as` is used only when returning the
	 * value (same reason as `SQLiteModel#withAutoFields`).
	 */
	private withAutoFields(input: Creatable<TTable>): TTable["$inferInsert"] {
		const now = Date.now();
		const values: Record<string, unknown> = { ...input };
		if ("id" in this.table && values.id === undefined) {
			values.id = this.idGenerator.generate();
		}
		if ("createdAt" in this.table && values.createdAt === undefined) {
			values.createdAt = now;
		}
		if ("updatedAt" in this.table && values.updatedAt === undefined) {
			values.updatedAt = now;
		}
		return values as TTable["$inferInsert"];
	}

	/**
	 * Returns `patch` with `updatedAt` (only if the table has it) overwritten with the
	 * current time. Uses `as` only when returning, for the same reason as
	 * `withAutoFields`.
	 */
	private withTouchedUpdatedAt(
		patch: Partial<TTable["$inferInsert"]>,
	): Partial<TTable["$inferInsert"]> {
		if (!("updatedAt" in this.table)) return patch;
		return { ...patch, updatedAt: Date.now() } as Partial<TTable["$inferInsert"]>;
	}

	/**
	 * Returns the `lockVersion` column used by `updateLocked`. Presence is checked at
	 * runtime with the same technique as `withAutoFields` (the `in` operator); throws
	 * with a clear message if the table has no `lockVersion` column.
	 */
	private lockVersionColumn(): MySqlColumn {
		if (!("lockVersion" in this.table)) {
			throw new Error(
				`MySqlModel#updateLocked: table "${getTableName(this.table)}" has no lockVersion column. ` +
					"Add a lockVersion column (integer, NOT NULL, initial value 0) to the table to use optimistic locking.",
			);
		}
		return (this.table as MySqlTable & { lockVersion: MySqlColumn }).lockVersion;
	}

	/**
	 * Verifies the presence of the `deletedAt` column used by `softDelete`/`restore`.
	 * Presence is checked at runtime with the same technique as `lockVersionColumn`
	 * (the `in` operator); throws with a clear message if the table has no `deletedAt`
	 * column.
	 */
	private assertDeletedAtColumn(): void {
		if (!("deletedAt" in this.table)) {
			throw new Error(
				`MySqlModel#softDelete: table "${getTableName(this.table)}" has no deletedAt column. ` +
					"Add a deletedAt column (bigint mode: number, nullable) to the table to use soft delete.",
			);
		}
	}

	/**
	 * Guard used by `listIn`/`groupedIn`/`retrieveMany` to check that the number of
	 * values passed to an `IN` clause doesn't exceed the third constructor argument
	 * `maxInValues`. Throws with a clear message if it's exceeded (same contract as
	 * `SQLiteModel#assertWithinMaxInValues`/`PgModel#assertWithinMaxInValues`).
	 */
	private assertWithinMaxInValues(length: number): void {
		if (length > this.maxInValues) {
			throw new Error(
				`MySqlModel: number of values passed to IN clause (${length}) exceeds the limit (${this.maxInValues}). ` +
					"Use paginate(where) for large-scale filtering.",
			);
		}
	}
}
