/**
 * Cloudflare Queues adapter for `JobQueue`. Takes a Queue binding (producer) via
 * constructor injection and `send`s messages shaped as `JobMessage` (`{ name, payload }`).
 * The consumer side (`queue_consumer.ts`) relies on this shape, looking up the job via
 * `message.body.name`.
 *
 * The class is named `CloudflareJobQueue` rather than `Queue` to avoid colliding with
 * Cloudflare's global `Queue<Body>` type (`src/worker.d.ts`, the ambient environment type
 * generated by wrangler) — the same consideration that leads `RouteHandler` to avoid Hono's
 * reserved names.
 *
 * Uses the Cloudflare Queues Producer API (`Queue#send`, the `MessageSendRequest` shape).
 * `enqueue`'s `options.delaySeconds` is passed through as-is to `Queue#send`'s second
 * argument, `QueueSendOptions.delaySeconds`, letting Cloudflare Queues handle the delayed
 * delivery. `options.priority` is only validated by `assertValidEnqueueOptions` and then
 * ignored, since Cloudflare Queues has no concept of priority (only the DB-backed queue
 * adapters interpret it).
 */
import type { Job } from "../jobs/job.js";
import type { EnqueueOptions } from "../jobs/job_queue.js";
import { assertValidEnqueueOptions, JobQueue } from "../jobs/job_queue.js";

/** Shape of the message `CloudflareJobQueue` sends. The consumer looks up the job by `name`. */
export type JobMessage = {
	readonly name: string;
	readonly payload: unknown;
};

/** `JobQueue` implementation backed by a Cloudflare Queues producer binding. */
export class CloudflareJobQueue extends JobQueue {
	constructor(private readonly queue: Queue<JobMessage>) {
		super();
	}

	/** Sends `job` and `payload` as a `JobMessage` to the underlying Cloudflare Queue. */
	async enqueue<TPayload>(
		job: Job<TPayload>,
		payload: TPayload,
		options?: EnqueueOptions,
	): Promise<void> {
		assertValidEnqueueOptions(options);

		const message = { name: job.name, payload };
		if (options?.delaySeconds === undefined) {
			await this.queue.send(message);
		} else {
			await this.queue.send(message, { delaySeconds: options.delaySeconds });
		}
	}
}
