/**
 * Message catalog for the unified admin panel's own UI labels (nav items, section
 * headings, action buttons, table column headers, etc.). This reuses the generic
 * `Translator`/`Catalog`/`CatalogBundle` machinery from `i18n/i18n.ts` (that module's
 * own `ja`/`en` catalog only covers framework-wide error pages; this is a separate,
 * admin-scoped catalog built the same way, per that module's doc comment inviting
 * apps to build their own catalogs).
 *
 * Scope: only labels the admin panel itself renders (dashboard/nav/jobs/settings/
 * audit/resource-CRUD chrome). Values the app supplies at runtime — `resource.label`,
 * `brand`, feature flag names, job `name`/`lastError`, audit `actor`/`action`/`target`,
 * and column names from `AdminResource#columns()` — are never translated here; they
 * are rendered as-is by the views regardless of the resolved language.
 *
 * Ten languages are implemented: `en` (default/fallback), `ja`, `zh`, `es`, `fr`,
 * `de`, `pt`, `ru`, `ko`, and `ar`. Adding another language is just adding another
 * entry to `adminCatalogBundle` with the same key set as `AdminCatalog`.
 */
import type { Context } from "hono";
import type { Catalog, CatalogBundle, TranslateParams } from "../i18n/i18n.js";
import { Translator } from "../i18n/i18n.js";

/** English catalog (default and fallback language for the admin panel). */
const en = {
	"nav.dashboard": "Dashboard",
	"nav.jobs": "Jobs",
	"nav.settings": "Settings",
	"nav.audit": "Audit log",
	"dashboard.welcome": "Welcome",
	"dashboard.empty": "No sections are wired up yet.",
	"breadcrumb.home": "Home",
	"index.resources": "Resources",
	"action.add": "Add",
	"action.change": "Change",
	"action.filter": "Filter",
	"filter.title": "Filter",
	"filter.all": "All",
	"action.search": "Search",
	"action.delete": "Delete",
	"action.actionLabel": "Action:",
	"action.run": "Run",
	"action.deleteSelected": "Delete selected {label}",
	"action.edit": "Edit",
	"action.detail": "Details",
	"action.save": "Save",
	"action.saveAddAnother": "Save and add another",
	"action.saveContinue": "Save and continue editing",
	"action.create": "New",
	"action.exportCsv": "Export CSV",
	"action.retry": "Retry",
	"action.backToList": "Back to list",
	"action.next": "Next",
	"col.name": "Name",
	"jobs.title": "Job operations",
	"jobs.pending": "Pending",
	"jobs.failed": "Failed",
	"jobs.emptyPending": "No pending jobs.",
	"jobs.emptyFailed": "No failed jobs.",
	"jobs.col.priority": "Priority",
	"jobs.col.runAt": "Scheduled",
	"jobs.col.attempts": "Attempts",
	"jobs.col.failedAt": "Failed at",
	"jobs.col.error": "Error",
	"audit.empty": "No audit logs found.",
	"audit.col.time": "Time",
	"audit.col.changes": "Changes",
	"resource.empty": "No records found.",
	"resource.newTitle": "Create {label}",
	"resource.editTitle": "Edit {label}",
	"resource.showTitle": "{label} details",
	"message.added": "The {label} was added successfully.",
	"message.changed": "The {label} was changed successfully.",
	"message.deleted": "The {label} was deleted successfully.",
	"message.deletedCount": "{count} {label} were deleted successfully.",
	"delete.confirm": "Are you sure you want to delete this {label}?",
	"delete.confirmSelected": "Are you sure you want to delete the selected {label}?",
	"delete.yes": "Yes, I'm sure",
	"delete.cancel": "No, take me back",
	"settings.flags": "Feature flags",
	"settings.flagsEmpty": "No flags to display.",
	"settings.enabled": "Enabled",
	"settings.disabled": "Disabled",
	"settings.enable": "Enable",
	"settings.disable": "Disable",
	"settings.maintenance": "Maintenance mode",
	"settings.current": "Current:",
	"settings.maintOn": "Under maintenance",
	"settings.maintOff": "Operating normally",
	"settings.maintEnable": "Start maintenance",
	"settings.maintDisable": "End maintenance",
	"dateHierarchy.all": "All dates",
	"auth.logIn": "Log in",
	"auth.logOut": "Log out",
	"auth.username": "Username",
	"auth.password": "Password",
	"auth.invalid": "Please enter a correct username and password.",
	"auth.tooManyAttempts": "Too many attempts. Try again later.",
	"auth.totpTitle": "Two-factor authentication",
	"auth.totpCode": "Authentication code",
	"auth.totpInvalid": "Invalid authentication code.",
	"a11y.skipToContent": "Skip to main content",
	"a11y.breadcrumb": "Breadcrumb",
	"a11y.dateDrilldown": "Date drilldown",
	"a11y.select": "Select",
	"a11y.selectRow": "Select {name}",
	"a11y.sortBy": "Sort by {column}",
	"a11y.page": "Page {n}",
	"a11y.viewItem": "View {name}",
	"a11y.editItem": "Edit {name}",
	"a11y.deleteItem": "Delete {name}",
	"a11y.addItem": "Add {label}",
	"a11y.changeItem": "Change {label}",
	"a11y.deleteInlineRow": "Delete this row",
	"nav.accounts": "Accounts",
	"accounts.users.singular": "user",
	"accounts.users.title": "Users",
	"accounts.users.empty": "No users found.",
	"accounts.users.col.username": "Username",
	"accounts.users.col.label": "Label",
	"accounts.users.col.active": "Active",
	"accounts.users.col.superuser": "Superuser",
	"accounts.users.col.lastLogin": "Last login",
	"accounts.users.newTitle": "Create user",
	"accounts.users.editTitle": "Edit user",
	"accounts.users.field.username": "Username",
	"accounts.users.field.password": "Password",
	"accounts.users.field.newPassword": "New password",
	"accounts.users.field.label": "Label",
	"accounts.users.field.active": "Active",
	"accounts.users.field.superuser": "Superuser",
	"accounts.users.field.permissions": "Permissions",
	"accounts.users.field.groups": "Groups",
	"accounts.users.unknownPermissions": "Also retains these unrecognized permissions: {list}",
	"accounts.users.changePassword": "Change password",
	"accounts.users.lastActiveSuperuserError":
		"Cannot deactivate, demote, or delete the last active superuser.",
	"accounts.users.saveError": "Could not save: {detail}",
	"accounts.users.groupsLink": "Groups",
	"accounts.groups.singular": "group",
	"accounts.groups.title": "Groups",
	"accounts.groups.empty": "No groups found.",
	"accounts.groups.col.name": "Name",
	"accounts.groups.col.permissionCount": "Permissions",
	"accounts.groups.usersLink": "Users",
	"accounts.groups.newTitle": "Create group",
	"accounts.groups.editTitle": "Edit group",
	"accounts.groups.field.name": "Name",
	"accounts.groups.field.permissions": "Permissions",
	"accounts.groups.unknownPermissions": "Also retains these unrecognized permissions: {list}",
	"accounts.groups.saveError": "Could not save: {detail}",
} satisfies Catalog;

/** Japanese catalog. Values mirror the literals previously hard-coded in each `.tsx` view. */
const ja = {
	"nav.dashboard": "ダッシュボード",
	"nav.jobs": "ジョブ",
	"nav.settings": "設定",
	"nav.audit": "監査ログ",
	"dashboard.welcome": "ようこそ",
	"dashboard.empty": "配線済みの区画はまだありません。",
	"breadcrumb.home": "ホーム",
	"index.resources": "リソース",
	"action.add": "追加",
	"action.change": "変更",
	"action.filter": "絞り込み",
	"filter.title": "絞り込み",
	"filter.all": "すべて",
	"action.search": "検索",
	"action.delete": "削除",
	"action.actionLabel": "アクション:",
	"action.run": "実行",
	"action.deleteSelected": "選択した {label} を削除",
	"action.edit": "編集",
	"action.detail": "詳細",
	"action.save": "保存",
	"action.saveAddAnother": "保存して続けて追加",
	"action.saveContinue": "保存して編集を続ける",
	"action.create": "新規作成",
	"action.exportCsv": "CSVエクスポート",
	"action.retry": "再実行",
	"action.backToList": "一覧へ戻る",
	"action.next": "次へ",
	"col.name": "名前",
	"jobs.title": "ジョブ運用",
	"jobs.pending": "保留中",
	"jobs.failed": "失敗",
	"jobs.emptyPending": "保留中のジョブはありません",
	"jobs.emptyFailed": "失敗したジョブはありません",
	"jobs.col.priority": "優先度",
	"jobs.col.runAt": "実行予定",
	"jobs.col.attempts": "試行",
	"jobs.col.failedAt": "失敗時刻",
	"jobs.col.error": "エラー",
	"audit.empty": "該当する監査ログはありません",
	"audit.col.time": "時刻",
	"audit.col.changes": "変更",
	"resource.empty": "該当するレコードがありません",
	"resource.newTitle": "{label}（新規作成）",
	"resource.editTitle": "{label}（編集）",
	"resource.showTitle": "{label}（詳細）",
	"message.added": "{label} を追加しました。",
	"message.changed": "{label} を変更しました。",
	"message.deleted": "{label} を削除しました。",
	"message.deletedCount": "{count} 件の {label} を削除しました。",
	"delete.confirm": "この {label} を削除してもよろしいですか？",
	"delete.confirmSelected": "選択した {label} を削除してもよろしいですか？",
	"delete.yes": "はい、削除します",
	"delete.cancel": "いいえ、戻る",
	"settings.flags": "フィーチャーフラグ",
	"settings.flagsEmpty": "表示対象のフラグはありません",
	"settings.enabled": "有効",
	"settings.disabled": "無効",
	"settings.enable": "有効化",
	"settings.disable": "無効化",
	"settings.maintenance": "メンテナンスモード",
	"settings.current": "現在:",
	"settings.maintOn": "メンテ中",
	"settings.maintOff": "通常運転",
	"settings.maintEnable": "メンテ開始",
	"settings.maintDisable": "メンテ解除",
	"dateHierarchy.all": "すべての日付",
	"auth.logIn": "ログイン",
	"auth.logOut": "ログアウト",
	"auth.username": "ユーザー名",
	"auth.password": "パスワード",
	"auth.invalid": "正しいユーザー名とパスワードを入力してください。",
	"auth.tooManyAttempts": "試行回数が上限に達しました。しばらくしてから再度お試しください。",
	"auth.totpTitle": "二段階認証",
	"auth.totpCode": "認証コード",
	"auth.totpInvalid": "認証コードが正しくありません。",
	"a11y.skipToContent": "本文へスキップ",
	"a11y.breadcrumb": "パンくず",
	"a11y.dateDrilldown": "日付ドリルダウン",
	"a11y.select": "選択",
	"a11y.selectRow": "{name} を選択",
	"a11y.sortBy": "{column} で並べ替え",
	"a11y.page": "{n} ページ目",
	"a11y.viewItem": "{name} を表示",
	"a11y.editItem": "{name} を編集",
	"a11y.deleteItem": "{name} を削除",
	"a11y.addItem": "{label} を追加",
	"a11y.changeItem": "{label} を変更",
	"a11y.deleteInlineRow": "この行を削除",
	"nav.accounts": "アカウント",
	"accounts.users.singular": "ユーザー",
	"accounts.users.title": "ユーザー",
	"accounts.users.empty": "ユーザーが見つかりません。",
	"accounts.users.col.username": "ユーザー名",
	"accounts.users.col.label": "ラベル",
	"accounts.users.col.active": "有効",
	"accounts.users.col.superuser": "スーパーユーザー",
	"accounts.users.col.lastLogin": "最終ログイン",
	"accounts.users.newTitle": "ユーザーを作成",
	"accounts.users.editTitle": "ユーザーを編集",
	"accounts.users.field.username": "ユーザー名",
	"accounts.users.field.password": "パスワード",
	"accounts.users.field.newPassword": "新しいパスワード",
	"accounts.users.field.label": "ラベル",
	"accounts.users.field.active": "有効",
	"accounts.users.field.superuser": "スーパーユーザー",
	"accounts.users.field.permissions": "権限",
	"accounts.users.field.groups": "グループ",
	"accounts.users.unknownPermissions": "認識できない次の権限も保持されています: {list}",
	"accounts.users.changePassword": "パスワードを変更",
	"accounts.users.lastActiveSuperuserError":
		"最後に残っているアクティブなスーパーユーザーを、無効化・降格・削除することはできません。",
	"accounts.users.saveError": "保存できませんでした: {detail}",
	"accounts.users.groupsLink": "グループ",
	"accounts.groups.singular": "グループ",
	"accounts.groups.title": "グループ",
	"accounts.groups.empty": "グループが見つかりません。",
	"accounts.groups.col.name": "名前",
	"accounts.groups.col.permissionCount": "権限数",
	"accounts.groups.usersLink": "ユーザー",
	"accounts.groups.newTitle": "グループを作成",
	"accounts.groups.editTitle": "グループを編集",
	"accounts.groups.field.name": "名前",
	"accounts.groups.field.permissions": "権限",
	"accounts.groups.unknownPermissions": "認識できない次の権限も保持されています: {list}",
	"accounts.groups.saveError": "保存できませんでした: {detail}",
} satisfies Catalog;

/** The key set of the admin panel's own catalog (`en` is authoritative; every other catalog mirrors the same keys). */
export type AdminCatalog = typeof en;

/** Simplified Chinese catalog. */
const zh = {
	"nav.dashboard": "仪表板",
	"nav.jobs": "任务",
	"nav.settings": "设置",
	"nav.audit": "审计日志",
	"dashboard.welcome": "欢迎",
	"dashboard.empty": "尚未接入任何模块。",
	"breadcrumb.home": "首页",
	"index.resources": "资源",
	"action.add": "添加",
	"action.change": "修改",
	"action.filter": "筛选",
	"filter.title": "筛选",
	"filter.all": "全部",
	"action.search": "搜索",
	"action.delete": "删除",
	"action.actionLabel": "操作：",
	"action.run": "执行",
	"action.deleteSelected": "删除所选{label}",
	"action.edit": "编辑",
	"action.detail": "详情",
	"action.save": "保存",
	"action.saveAddAnother": "保存并新增",
	"action.saveContinue": "保存并继续编辑",
	"action.create": "新建",
	"action.exportCsv": "导出 CSV",
	"action.retry": "重试",
	"action.backToList": "返回列表",
	"action.next": "下一页",
	"col.name": "名称",
	"jobs.title": "任务管理",
	"jobs.pending": "待处理",
	"jobs.failed": "失败",
	"jobs.emptyPending": "没有待处理的任务。",
	"jobs.emptyFailed": "没有失败的任务。",
	"jobs.col.priority": "优先级",
	"jobs.col.runAt": "计划时间",
	"jobs.col.attempts": "尝试次数",
	"jobs.col.failedAt": "失败时间",
	"jobs.col.error": "错误",
	"audit.empty": "未找到审计日志。",
	"audit.col.time": "时间",
	"audit.col.changes": "变更",
	"resource.empty": "未找到记录。",
	"resource.newTitle": "新建{label}",
	"resource.editTitle": "编辑{label}",
	"resource.showTitle": "{label}详情",
	"message.added": "{label} 添加成功。",
	"message.changed": "{label} 修改成功。",
	"message.deleted": "{label} 删除成功。",
	"message.deletedCount": "已成功删除 {count} 个{label}。",
	"delete.confirm": "确定要删除这个 {label} 吗？",
	"delete.confirmSelected": "确定要删除所选的 {label} 吗？",
	"delete.yes": "是的，我确定",
	"delete.cancel": "不，返回",
	"settings.flags": "功能开关",
	"settings.flagsEmpty": "没有可显示的开关。",
	"settings.enabled": "已启用",
	"settings.disabled": "已禁用",
	"settings.enable": "启用",
	"settings.disable": "禁用",
	"settings.maintenance": "维护模式",
	"settings.current": "当前：",
	"settings.maintOn": "维护中",
	"settings.maintOff": "正常运行",
	"settings.maintEnable": "开启维护",
	"settings.maintDisable": "解除维护",
	"dateHierarchy.all": "所有日期",
	"auth.logIn": "登录",
	"auth.logOut": "退出登录",
	"auth.username": "用户名",
	"auth.password": "密码",
	"auth.invalid": "请输入正确的用户名和密码。",
	"auth.tooManyAttempts": "尝试次数过多，请稍后再试。",
	"auth.totpTitle": "双重验证",
	"auth.totpCode": "验证码",
	"auth.totpInvalid": "验证码无效。",
	"a11y.skipToContent": "跳至主要内容",
	"a11y.breadcrumb": "面包屑导航",
	"a11y.dateDrilldown": "日期下钻导航",
	"a11y.select": "选择",
	"a11y.selectRow": "选择 {name}",
	"a11y.sortBy": "按 {column} 排序",
	"a11y.page": "第 {n} 页",
	"a11y.viewItem": "查看 {name}",
	"a11y.editItem": "编辑 {name}",
	"a11y.deleteItem": "删除 {name}",
	"a11y.addItem": "添加 {label}",
	"a11y.changeItem": "修改 {label}",
	"a11y.deleteInlineRow": "删除此行",
	"nav.accounts": "账户",
	"accounts.users.singular": "用户",
	"accounts.users.title": "用户",
	"accounts.users.empty": "未找到用户。",
	"accounts.users.col.username": "用户名",
	"accounts.users.col.label": "标签",
	"accounts.users.col.active": "已激活",
	"accounts.users.col.superuser": "超级用户",
	"accounts.users.col.lastLogin": "最后登录",
	"accounts.users.newTitle": "新建用户",
	"accounts.users.editTitle": "编辑用户",
	"accounts.users.field.username": "用户名",
	"accounts.users.field.password": "密码",
	"accounts.users.field.newPassword": "新密码",
	"accounts.users.field.label": "标签",
	"accounts.users.field.active": "已激活",
	"accounts.users.field.superuser": "超级用户",
	"accounts.users.field.permissions": "权限",
	"accounts.users.field.groups": "分组",
	"accounts.users.unknownPermissions": "还保留了以下无法识别的权限：{list}",
	"accounts.users.changePassword": "修改密码",
	"accounts.users.lastActiveSuperuserError": "无法停用、降级或删除最后一个活跃的超级用户。",
	"accounts.users.saveError": "无法保存：{detail}",
	"accounts.users.groupsLink": "分组",
	"accounts.groups.singular": "分组",
	"accounts.groups.title": "分组",
	"accounts.groups.empty": "未找到分组。",
	"accounts.groups.col.name": "名称",
	"accounts.groups.col.permissionCount": "权限数",
	"accounts.groups.usersLink": "用户",
	"accounts.groups.newTitle": "新建分组",
	"accounts.groups.editTitle": "编辑分组",
	"accounts.groups.field.name": "名称",
	"accounts.groups.field.permissions": "权限",
	"accounts.groups.unknownPermissions": "还保留了以下无法识别的权限：{list}",
	"accounts.groups.saveError": "无法保存：{detail}",
} satisfies AdminCatalog;

/** Spanish catalog. */
const es = {
	"nav.dashboard": "Panel",
	"nav.jobs": "Tareas",
	"nav.settings": "Configuración",
	"nav.audit": "Registro de auditoría",
	"dashboard.welcome": "Bienvenido",
	"dashboard.empty": "Aún no hay secciones configuradas.",
	"breadcrumb.home": "Inicio",
	"index.resources": "Recursos",
	"action.add": "Añadir",
	"action.change": "Editar",
	"action.filter": "Filtrar",
	"filter.title": "Filtro",
	"filter.all": "Todos",
	"action.search": "Buscar",
	"action.delete": "Eliminar",
	"action.actionLabel": "Acción:",
	"action.run": "Ejecutar",
	"action.deleteSelected": "Eliminar {label} seleccionados",
	"action.edit": "Editar",
	"action.detail": "Detalles",
	"action.save": "Guardar",
	"action.saveAddAnother": "Guardar y añadir otro",
	"action.saveContinue": "Guardar y continuar editando",
	"action.create": "Nuevo",
	"action.exportCsv": "Exportar CSV",
	"action.retry": "Reintentar",
	"action.backToList": "Volver a la lista",
	"action.next": "Siguiente",
	"col.name": "Nombre",
	"jobs.title": "Operaciones de tareas",
	"jobs.pending": "Pendientes",
	"jobs.failed": "Fallidas",
	"jobs.emptyPending": "No hay tareas pendientes.",
	"jobs.emptyFailed": "No hay tareas fallidas.",
	"jobs.col.priority": "Prioridad",
	"jobs.col.runAt": "Programada",
	"jobs.col.attempts": "Intentos",
	"jobs.col.failedAt": "Fecha de fallo",
	"jobs.col.error": "Error",
	"audit.empty": "No se encontraron registros de auditoría.",
	"audit.col.time": "Hora",
	"audit.col.changes": "Cambios",
	"resource.empty": "No se encontraron registros.",
	"resource.newTitle": "Crear {label}",
	"resource.editTitle": "Editar {label}",
	"resource.showTitle": "Detalles de {label}",
	"message.added": "El {label} se añadió correctamente.",
	"message.changed": "El {label} se modificó correctamente.",
	"message.deleted": "El {label} se eliminó correctamente.",
	"message.deletedCount": "Se eliminaron {count} {label} correctamente.",
	"delete.confirm": "¿Está seguro de que quiere eliminar este {label}?",
	"delete.confirmSelected": "¿Está seguro de que quiere eliminar los {label} seleccionados?",
	"delete.yes": "Sí, estoy seguro",
	"delete.cancel": "No, volver atrás",
	"settings.flags": "Indicadores de funciones",
	"settings.flagsEmpty": "No hay indicadores para mostrar.",
	"settings.enabled": "Habilitado",
	"settings.disabled": "Deshabilitado",
	"settings.enable": "Habilitar",
	"settings.disable": "Deshabilitar",
	"settings.maintenance": "Modo de mantenimiento",
	"settings.current": "Actual:",
	"settings.maintOn": "En mantenimiento",
	"settings.maintOff": "Funcionamiento normal",
	"settings.maintEnable": "Iniciar mantenimiento",
	"settings.maintDisable": "Finalizar mantenimiento",
	"dateHierarchy.all": "Todas las fechas",
	"auth.logIn": "Iniciar sesión",
	"auth.logOut": "Cerrar sesión",
	"auth.username": "Usuario",
	"auth.password": "Contraseña",
	"auth.invalid": "Introduzca un nombre de usuario y una contraseña correctos.",
	"auth.tooManyAttempts": "Demasiados intentos. Inténtelo de nuevo más tarde.",
	"auth.totpTitle": "Autenticación de dos factores",
	"auth.totpCode": "Código de autenticación",
	"auth.totpInvalid": "Código de autenticación no válido.",
	"a11y.skipToContent": "Saltar al contenido principal",
	"a11y.breadcrumb": "Ruta de navegación",
	"a11y.dateDrilldown": "Navegación por fecha",
	"a11y.select": "Seleccionar",
	"a11y.selectRow": "Seleccionar {name}",
	"a11y.sortBy": "Ordenar por {column}",
	"a11y.page": "Página {n}",
	"a11y.viewItem": "Ver {name}",
	"a11y.editItem": "Editar {name}",
	"a11y.deleteItem": "Eliminar {name}",
	"a11y.addItem": "Añadir {label}",
	"a11y.changeItem": "Editar {label}",
	"a11y.deleteInlineRow": "Eliminar esta fila",
	"nav.accounts": "Cuentas",
	"accounts.users.singular": "usuario",
	"accounts.users.title": "Usuarios",
	"accounts.users.empty": "No se encontraron usuarios.",
	"accounts.users.col.username": "Usuario",
	"accounts.users.col.label": "Etiqueta",
	"accounts.users.col.active": "Activo",
	"accounts.users.col.superuser": "Superusuario",
	"accounts.users.col.lastLogin": "Último acceso",
	"accounts.users.newTitle": "Crear usuario",
	"accounts.users.editTitle": "Editar usuario",
	"accounts.users.field.username": "Usuario",
	"accounts.users.field.password": "Contraseña",
	"accounts.users.field.newPassword": "Nueva contraseña",
	"accounts.users.field.label": "Etiqueta",
	"accounts.users.field.active": "Activo",
	"accounts.users.field.superuser": "Superusuario",
	"accounts.users.field.permissions": "Permisos",
	"accounts.users.field.groups": "Grupos",
	"accounts.users.unknownPermissions": "También conserva estos permisos no reconocidos: {list}",
	"accounts.users.changePassword": "Cambiar contraseña",
	"accounts.users.lastActiveSuperuserError":
		"No se puede desactivar, degradar ni eliminar al último superusuario activo.",
	"accounts.users.saveError": "No se pudo guardar: {detail}",
	"accounts.users.groupsLink": "Grupos",
	"accounts.groups.singular": "grupo",
	"accounts.groups.title": "Grupos",
	"accounts.groups.empty": "No se encontraron grupos.",
	"accounts.groups.col.name": "Nombre",
	"accounts.groups.col.permissionCount": "Permisos",
	"accounts.groups.usersLink": "Usuarios",
	"accounts.groups.newTitle": "Crear grupo",
	"accounts.groups.editTitle": "Editar grupo",
	"accounts.groups.field.name": "Nombre",
	"accounts.groups.field.permissions": "Permisos",
	"accounts.groups.unknownPermissions": "También conserva estos permisos no reconocidos: {list}",
	"accounts.groups.saveError": "No se pudo guardar: {detail}",
} satisfies AdminCatalog;

/** French catalog. */
const fr = {
	"nav.dashboard": "Tableau de bord",
	"nav.jobs": "Tâches",
	"nav.settings": "Paramètres",
	"nav.audit": "Journal d'audit",
	"dashboard.welcome": "Bienvenue",
	"dashboard.empty": "Aucune section n'est encore configurée.",
	"breadcrumb.home": "Accueil",
	"index.resources": "Ressources",
	"action.add": "Ajouter",
	"action.change": "Modifier",
	"action.filter": "Filtrer",
	"filter.title": "Filtre",
	"filter.all": "Tous",
	"action.search": "Rechercher",
	"action.delete": "Supprimer",
	"action.actionLabel": "Action :",
	"action.run": "Exécuter",
	"action.deleteSelected": "Supprimer les {label} sélectionnés",
	"action.edit": "Modifier",
	"action.detail": "Détails",
	"action.save": "Enregistrer",
	"action.saveAddAnother": "Enregistrer et ajouter un autre",
	"action.saveContinue": "Enregistrer et continuer les modifications",
	"action.create": "Nouveau",
	"action.exportCsv": "Exporter en CSV",
	"action.retry": "Réessayer",
	"action.backToList": "Retour à la liste",
	"action.next": "Suivant",
	"col.name": "Nom",
	"jobs.title": "Gestion des tâches",
	"jobs.pending": "En attente",
	"jobs.failed": "Échouées",
	"jobs.emptyPending": "Aucune tâche en attente.",
	"jobs.emptyFailed": "Aucune tâche échouée.",
	"jobs.col.priority": "Priorité",
	"jobs.col.runAt": "Planifiée",
	"jobs.col.attempts": "Tentatives",
	"jobs.col.failedAt": "Date d'échec",
	"jobs.col.error": "Erreur",
	"audit.empty": "Aucun journal d'audit trouvé.",
	"audit.col.time": "Heure",
	"audit.col.changes": "Modifications",
	"resource.empty": "Aucun enregistrement trouvé.",
	"resource.newTitle": "Créer {label}",
	"resource.editTitle": "Modifier {label}",
	"resource.showTitle": "Détails de {label}",
	"message.added": "Le {label} a été ajouté avec succès.",
	"message.changed": "Le {label} a été modifié avec succès.",
	"message.deleted": "Le {label} a été supprimé avec succès.",
	"message.deletedCount": "{count} {label} ont été supprimés avec succès.",
	"delete.confirm": "Êtes-vous sûr de vouloir supprimer ce {label} ?",
	"delete.confirmSelected": "Êtes-vous sûr de vouloir supprimer les {label} sélectionnés ?",
	"delete.yes": "Oui, je suis sûr",
	"delete.cancel": "Non, revenir en arrière",
	"settings.flags": "Indicateurs de fonctionnalités",
	"settings.flagsEmpty": "Aucun indicateur à afficher.",
	"settings.enabled": "Activé",
	"settings.disabled": "Désactivé",
	"settings.enable": "Activer",
	"settings.disable": "Désactiver",
	"settings.maintenance": "Mode maintenance",
	"settings.current": "Actuel :",
	"settings.maintOn": "En maintenance",
	"settings.maintOff": "Fonctionnement normal",
	"settings.maintEnable": "Démarrer la maintenance",
	"settings.maintDisable": "Terminer la maintenance",
	"dateHierarchy.all": "Toutes les dates",
	"auth.logIn": "Connexion",
	"auth.logOut": "Déconnexion",
	"auth.username": "Nom d'utilisateur",
	"auth.password": "Mot de passe",
	"auth.invalid": "Veuillez saisir un nom d'utilisateur et un mot de passe corrects.",
	"auth.tooManyAttempts": "Trop de tentatives. Réessayez plus tard.",
	"auth.totpTitle": "Authentification à deux facteurs",
	"auth.totpCode": "Code d'authentification",
	"auth.totpInvalid": "Code d'authentification invalide.",
	"a11y.skipToContent": "Passer au contenu principal",
	"a11y.breadcrumb": "Fil d'Ariane",
	"a11y.dateDrilldown": "Navigation par date",
	"a11y.select": "Sélectionner",
	"a11y.selectRow": "Sélectionner {name}",
	"a11y.sortBy": "Trier par {column}",
	"a11y.page": "Page {n}",
	"a11y.viewItem": "Voir {name}",
	"a11y.editItem": "Modifier {name}",
	"a11y.deleteItem": "Supprimer {name}",
	"a11y.addItem": "Ajouter {label}",
	"a11y.changeItem": "Modifier {label}",
	"a11y.deleteInlineRow": "Supprimer cette ligne",
	"nav.accounts": "Comptes",
	"accounts.users.singular": "utilisateur",
	"accounts.users.title": "Utilisateurs",
	"accounts.users.empty": "Aucun utilisateur trouvé.",
	"accounts.users.col.username": "Nom d'utilisateur",
	"accounts.users.col.label": "Libellé",
	"accounts.users.col.active": "Actif",
	"accounts.users.col.superuser": "Superutilisateur",
	"accounts.users.col.lastLogin": "Dernière connexion",
	"accounts.users.newTitle": "Créer un utilisateur",
	"accounts.users.editTitle": "Modifier l'utilisateur",
	"accounts.users.field.username": "Nom d'utilisateur",
	"accounts.users.field.password": "Mot de passe",
	"accounts.users.field.newPassword": "Nouveau mot de passe",
	"accounts.users.field.label": "Libellé",
	"accounts.users.field.active": "Actif",
	"accounts.users.field.superuser": "Superutilisateur",
	"accounts.users.field.permissions": "Autorisations",
	"accounts.users.field.groups": "Groupes",
	"accounts.users.unknownPermissions":
		"Conserve également ces autorisations non reconnues : {list}",
	"accounts.users.changePassword": "Changer le mot de passe",
	"accounts.users.lastActiveSuperuserError":
		"Impossible de désactiver, rétrograder ou supprimer le dernier superutilisateur actif.",
	"accounts.users.saveError": "Impossible d'enregistrer : {detail}",
	"accounts.users.groupsLink": "Groupes",
	"accounts.groups.singular": "groupe",
	"accounts.groups.title": "Groupes",
	"accounts.groups.empty": "Aucun groupe trouvé.",
	"accounts.groups.col.name": "Nom",
	"accounts.groups.col.permissionCount": "Autorisations",
	"accounts.groups.usersLink": "Utilisateurs",
	"accounts.groups.newTitle": "Créer un groupe",
	"accounts.groups.editTitle": "Modifier le groupe",
	"accounts.groups.field.name": "Nom",
	"accounts.groups.field.permissions": "Autorisations",
	"accounts.groups.unknownPermissions":
		"Conserve également ces autorisations non reconnues : {list}",
	"accounts.groups.saveError": "Impossible d'enregistrer : {detail}",
} satisfies AdminCatalog;

/** German catalog. */
const de = {
	"nav.dashboard": "Dashboard",
	"nav.jobs": "Aufgaben",
	"nav.settings": "Einstellungen",
	"nav.audit": "Audit-Protokoll",
	"dashboard.welcome": "Willkommen",
	"dashboard.empty": "Es sind noch keine Bereiche eingerichtet.",
	"breadcrumb.home": "Startseite",
	"index.resources": "Ressourcen",
	"action.add": "Hinzufügen",
	"action.change": "Ändern",
	"action.filter": "Filtern",
	"filter.title": "Filter",
	"filter.all": "Alle",
	"action.search": "Suchen",
	"action.delete": "Löschen",
	"action.actionLabel": "Aktion:",
	"action.run": "Ausführen",
	"action.deleteSelected": "Ausgewählte {label} löschen",
	"action.edit": "Bearbeiten",
	"action.detail": "Details",
	"action.save": "Speichern",
	"action.saveAddAnother": "Sichern und neu hinzufügen",
	"action.saveContinue": "Sichern und weiter bearbeiten",
	"action.create": "Neu",
	"action.exportCsv": "CSV exportieren",
	"action.retry": "Wiederholen",
	"action.backToList": "Zurück zur Liste",
	"action.next": "Weiter",
	"col.name": "Name",
	"jobs.title": "Aufgabenverwaltung",
	"jobs.pending": "Ausstehend",
	"jobs.failed": "Fehlgeschlagen",
	"jobs.emptyPending": "Keine ausstehenden Aufgaben.",
	"jobs.emptyFailed": "Keine fehlgeschlagenen Aufgaben.",
	"jobs.col.priority": "Priorität",
	"jobs.col.runAt": "Geplant",
	"jobs.col.attempts": "Versuche",
	"jobs.col.failedAt": "Fehlgeschlagen am",
	"jobs.col.error": "Fehler",
	"audit.empty": "Keine Audit-Protokolle gefunden.",
	"audit.col.time": "Zeit",
	"audit.col.changes": "Änderungen",
	"resource.empty": "Keine Datensätze gefunden.",
	"resource.newTitle": "{label} erstellen",
	"resource.editTitle": "{label} bearbeiten",
	"resource.showTitle": "Details zu {label}",
	"message.added": "Das {label} wurde erfolgreich hinzugefügt.",
	"message.changed": "Das {label} wurde erfolgreich geändert.",
	"message.deleted": "Das {label} wurde erfolgreich gelöscht.",
	"message.deletedCount": "{count} {label} wurden erfolgreich gelöscht.",
	"delete.confirm": "Sind Sie sicher, dass Sie dieses {label} löschen möchten?",
	"delete.confirmSelected": "Sind Sie sicher, dass Sie die ausgewählten {label} löschen möchten?",
	"delete.yes": "Ja, ich bin sicher",
	"delete.cancel": "Nein, zurück",
	"settings.flags": "Feature-Flags",
	"settings.flagsEmpty": "Keine Flags zum Anzeigen.",
	"settings.enabled": "Aktiviert",
	"settings.disabled": "Deaktiviert",
	"settings.enable": "Aktivieren",
	"settings.disable": "Deaktivieren",
	"settings.maintenance": "Wartungsmodus",
	"settings.current": "Aktuell:",
	"settings.maintOn": "In Wartung",
	"settings.maintOff": "Normalbetrieb",
	"settings.maintEnable": "Wartung starten",
	"settings.maintDisable": "Wartung beenden",
	"dateHierarchy.all": "Alle Daten",
	"auth.logIn": "Anmelden",
	"auth.logOut": "Abmelden",
	"auth.username": "Benutzername",
	"auth.password": "Passwort",
	"auth.invalid": "Bitte geben Sie einen korrekten Benutzernamen und ein korrektes Passwort ein.",
	"auth.tooManyAttempts": "Zu viele Versuche. Bitte versuchen Sie es später erneut.",
	"auth.totpTitle": "Zwei-Faktor-Authentifizierung",
	"auth.totpCode": "Authentifizierungscode",
	"auth.totpInvalid": "Ungültiger Authentifizierungscode.",
	"a11y.skipToContent": "Zum Hauptinhalt springen",
	"a11y.breadcrumb": "Brotkrümelnavigation",
	"a11y.dateDrilldown": "Datums-Drilldown",
	"a11y.select": "Auswählen",
	"a11y.selectRow": "{name} auswählen",
	"a11y.sortBy": "Nach {column} sortieren",
	"a11y.page": "Seite {n}",
	"a11y.viewItem": "{name} anzeigen",
	"a11y.editItem": "{name} bearbeiten",
	"a11y.deleteItem": "{name} löschen",
	"a11y.addItem": "{label} hinzufügen",
	"a11y.changeItem": "{label} ändern",
	"a11y.deleteInlineRow": "Diese Zeile löschen",
	"nav.accounts": "Konten",
	"accounts.users.singular": "Benutzer",
	"accounts.users.title": "Benutzer",
	"accounts.users.empty": "Keine Benutzer gefunden.",
	"accounts.users.col.username": "Benutzername",
	"accounts.users.col.label": "Bezeichnung",
	"accounts.users.col.active": "Aktiv",
	"accounts.users.col.superuser": "Superuser",
	"accounts.users.col.lastLogin": "Letzte Anmeldung",
	"accounts.users.newTitle": "Benutzer erstellen",
	"accounts.users.editTitle": "Benutzer bearbeiten",
	"accounts.users.field.username": "Benutzername",
	"accounts.users.field.password": "Passwort",
	"accounts.users.field.newPassword": "Neues Passwort",
	"accounts.users.field.label": "Bezeichnung",
	"accounts.users.field.active": "Aktiv",
	"accounts.users.field.superuser": "Superuser",
	"accounts.users.field.permissions": "Berechtigungen",
	"accounts.users.field.groups": "Gruppen",
	"accounts.users.unknownPermissions":
		"Behält außerdem diese nicht erkannten Berechtigungen: {list}",
	"accounts.users.changePassword": "Passwort ändern",
	"accounts.users.lastActiveSuperuserError":
		"Der letzte aktive Superuser kann nicht deaktiviert, herabgestuft oder gelöscht werden.",
	"accounts.users.saveError": "Konnte nicht gespeichert werden: {detail}",
	"accounts.users.groupsLink": "Gruppen",
	"accounts.groups.singular": "Gruppe",
	"accounts.groups.title": "Gruppen",
	"accounts.groups.empty": "Keine Gruppen gefunden.",
	"accounts.groups.col.name": "Name",
	"accounts.groups.col.permissionCount": "Berechtigungen",
	"accounts.groups.usersLink": "Benutzer",
	"accounts.groups.newTitle": "Gruppe erstellen",
	"accounts.groups.editTitle": "Gruppe bearbeiten",
	"accounts.groups.field.name": "Name",
	"accounts.groups.field.permissions": "Berechtigungen",
	"accounts.groups.unknownPermissions":
		"Behält außerdem diese nicht erkannten Berechtigungen: {list}",
	"accounts.groups.saveError": "Konnte nicht gespeichert werden: {detail}",
} satisfies AdminCatalog;

/** Brazilian Portuguese catalog. */
const pt = {
	"nav.dashboard": "Painel",
	"nav.jobs": "Tarefas",
	"nav.settings": "Configurações",
	"nav.audit": "Registro de auditoria",
	"dashboard.welcome": "Bem-vindo",
	"dashboard.empty": "Nenhuma seção configurada ainda.",
	"breadcrumb.home": "Início",
	"index.resources": "Recursos",
	"action.add": "Adicionar",
	"action.change": "Alterar",
	"action.filter": "Filtrar",
	"filter.title": "Filtro",
	"filter.all": "Todos",
	"action.search": "Buscar",
	"action.delete": "Excluir",
	"action.actionLabel": "Ação:",
	"action.run": "Executar",
	"action.deleteSelected": "Excluir {label} selecionados",
	"action.edit": "Editar",
	"action.detail": "Detalhes",
	"action.save": "Salvar",
	"action.saveAddAnother": "Salvar e adicionar outro",
	"action.saveContinue": "Salvar e continuar editando",
	"action.create": "Novo",
	"action.exportCsv": "Exportar CSV",
	"action.retry": "Tentar novamente",
	"action.backToList": "Voltar à lista",
	"action.next": "Próximo",
	"col.name": "Nome",
	"jobs.title": "Operações de tarefas",
	"jobs.pending": "Pendentes",
	"jobs.failed": "Com falha",
	"jobs.emptyPending": "Nenhuma tarefa pendente.",
	"jobs.emptyFailed": "Nenhuma tarefa com falha.",
	"jobs.col.priority": "Prioridade",
	"jobs.col.runAt": "Agendada",
	"jobs.col.attempts": "Tentativas",
	"jobs.col.failedAt": "Falhou em",
	"jobs.col.error": "Erro",
	"audit.empty": "Nenhum registro de auditoria encontrado.",
	"audit.col.time": "Horário",
	"audit.col.changes": "Alterações",
	"resource.empty": "Nenhum registro encontrado.",
	"resource.newTitle": "Criar {label}",
	"resource.editTitle": "Editar {label}",
	"resource.showTitle": "Detalhes de {label}",
	"message.added": "O {label} foi adicionado com sucesso.",
	"message.changed": "O {label} foi alterado com sucesso.",
	"message.deleted": "O {label} foi excluído com sucesso.",
	"message.deletedCount": "{count} {label} foram excluídos com sucesso.",
	"delete.confirm": "Tem certeza de que deseja excluir este {label}?",
	"delete.confirmSelected": "Tem certeza de que deseja excluir os {label} selecionados?",
	"delete.yes": "Sim, tenho certeza",
	"delete.cancel": "Não, voltar",
	"settings.flags": "Feature flags",
	"settings.flagsEmpty": "Nenhuma flag para exibir.",
	"settings.enabled": "Ativado",
	"settings.disabled": "Desativado",
	"settings.enable": "Ativar",
	"settings.disable": "Desativar",
	"settings.maintenance": "Modo de manutenção",
	"settings.current": "Atual:",
	"settings.maintOn": "Em manutenção",
	"settings.maintOff": "Operação normal",
	"settings.maintEnable": "Iniciar manutenção",
	"settings.maintDisable": "Encerrar manutenção",
	"dateHierarchy.all": "Todas as datas",
	"auth.logIn": "Entrar",
	"auth.logOut": "Sair",
	"auth.username": "Nome de usuário",
	"auth.password": "Senha",
	"auth.invalid": "Digite um nome de usuário e uma senha corretos.",
	"auth.tooManyAttempts": "Muitas tentativas. Tente novamente mais tarde.",
	"auth.totpTitle": "Autenticação de dois fatores",
	"auth.totpCode": "Código de autenticação",
	"auth.totpInvalid": "Código de autenticação inválido.",
	"a11y.skipToContent": "Pular para o conteúdo principal",
	"a11y.breadcrumb": "Trilha de navegação",
	"a11y.dateDrilldown": "Navegação por data",
	"a11y.select": "Selecionar",
	"a11y.selectRow": "Selecionar {name}",
	"a11y.sortBy": "Ordenar por {column}",
	"a11y.page": "Página {n}",
	"a11y.viewItem": "Ver {name}",
	"a11y.editItem": "Editar {name}",
	"a11y.deleteItem": "Excluir {name}",
	"a11y.addItem": "Adicionar {label}",
	"a11y.changeItem": "Alterar {label}",
	"a11y.deleteInlineRow": "Excluir esta linha",
	"nav.accounts": "Contas",
	"accounts.users.singular": "usuário",
	"accounts.users.title": "Usuários",
	"accounts.users.empty": "Nenhum usuário encontrado.",
	"accounts.users.col.username": "Nome de usuário",
	"accounts.users.col.label": "Rótulo",
	"accounts.users.col.active": "Ativo",
	"accounts.users.col.superuser": "Superusuário",
	"accounts.users.col.lastLogin": "Último acesso",
	"accounts.users.newTitle": "Criar usuário",
	"accounts.users.editTitle": "Editar usuário",
	"accounts.users.field.username": "Nome de usuário",
	"accounts.users.field.password": "Senha",
	"accounts.users.field.newPassword": "Nova senha",
	"accounts.users.field.label": "Rótulo",
	"accounts.users.field.active": "Ativo",
	"accounts.users.field.superuser": "Superusuário",
	"accounts.users.field.permissions": "Permissões",
	"accounts.users.field.groups": "Grupos",
	"accounts.users.unknownPermissions": "Também mantém estas permissões não reconhecidas: {list}",
	"accounts.users.changePassword": "Alterar senha",
	"accounts.users.lastActiveSuperuserError":
		"Não é possível desativar, rebaixar ou excluir o último superusuário ativo.",
	"accounts.users.saveError": "Não foi possível salvar: {detail}",
	"accounts.users.groupsLink": "Grupos",
	"accounts.groups.singular": "grupo",
	"accounts.groups.title": "Grupos",
	"accounts.groups.empty": "Nenhum grupo encontrado.",
	"accounts.groups.col.name": "Nome",
	"accounts.groups.col.permissionCount": "Permissões",
	"accounts.groups.usersLink": "Usuários",
	"accounts.groups.newTitle": "Criar grupo",
	"accounts.groups.editTitle": "Editar grupo",
	"accounts.groups.field.name": "Nome",
	"accounts.groups.field.permissions": "Permissões",
	"accounts.groups.unknownPermissions": "Também mantém estas permissões não reconhecidas: {list}",
	"accounts.groups.saveError": "Não foi possível salvar: {detail}",
} satisfies AdminCatalog;

/** Russian catalog. */
const ru = {
	"nav.dashboard": "Панель",
	"nav.jobs": "Задачи",
	"nav.settings": "Настройки",
	"nav.audit": "Журнал аудита",
	"dashboard.welcome": "Добро пожаловать",
	"dashboard.empty": "Разделы ещё не настроены.",
	"breadcrumb.home": "Главная",
	"index.resources": "Ресурсы",
	"action.add": "Добавить",
	"action.change": "Изменить",
	"action.filter": "Фильтр",
	"filter.title": "Фильтр",
	"filter.all": "Все",
	"action.search": "Поиск",
	"action.delete": "Удалить",
	"action.actionLabel": "Действие:",
	"action.run": "Выполнить",
	"action.deleteSelected": "Удалить выбранные {label}",
	"action.edit": "Изменить",
	"action.detail": "Подробности",
	"action.save": "Сохранить",
	"action.saveAddAnother": "Сохранить и добавить другой объект",
	"action.saveContinue": "Сохранить и продолжить редактирование",
	"action.create": "Создать",
	"action.exportCsv": "Экспорт в CSV",
	"action.retry": "Повторить",
	"action.backToList": "Назад к списку",
	"action.next": "Далее",
	"col.name": "Имя",
	"jobs.title": "Управление задачами",
	"jobs.pending": "В ожидании",
	"jobs.failed": "Неуспешные",
	"jobs.emptyPending": "Нет ожидающих задач.",
	"jobs.emptyFailed": "Нет неуспешных задач.",
	"jobs.col.priority": "Приоритет",
	"jobs.col.runAt": "Запланировано",
	"jobs.col.attempts": "Попытки",
	"jobs.col.failedAt": "Время сбоя",
	"jobs.col.error": "Ошибка",
	"audit.empty": "Записи аудита не найдены.",
	"audit.col.time": "Время",
	"audit.col.changes": "Изменения",
	"resource.empty": "Записи не найдены.",
	"resource.newTitle": "Создать {label}",
	"resource.editTitle": "Изменить {label}",
	"resource.showTitle": "Подробности: {label}",
	"message.added": "{label} успешно добавлен.",
	"message.changed": "{label} успешно изменён.",
	"message.deleted": "{label} успешно удалён.",
	"message.deletedCount": "{count} {label} успешно удалено.",
	"delete.confirm": "Вы уверены, что хотите удалить этот {label}?",
	"delete.confirmSelected": "Вы уверены, что хотите удалить выбранные {label}?",
	"delete.yes": "Да, я уверен",
	"delete.cancel": "Нет, вернуться назад",
	"settings.flags": "Флаги функций",
	"settings.flagsEmpty": "Нет флагов для отображения.",
	"settings.enabled": "Включено",
	"settings.disabled": "Отключено",
	"settings.enable": "Включить",
	"settings.disable": "Отключить",
	"settings.maintenance": "Режим обслуживания",
	"settings.current": "Текущее:",
	"settings.maintOn": "На обслуживании",
	"settings.maintOff": "Работает нормально",
	"settings.maintEnable": "Начать обслуживание",
	"settings.maintDisable": "Завершить обслуживание",
	"dateHierarchy.all": "Все даты",
	"auth.logIn": "Войти",
	"auth.logOut": "Выйти",
	"auth.username": "Имя пользователя",
	"auth.password": "Пароль",
	"auth.invalid": "Пожалуйста, введите правильные имя пользователя и пароль.",
	"auth.tooManyAttempts": "Слишком много попыток. Повторите попытку позже.",
	"auth.totpTitle": "Двухфакторная аутентификация",
	"auth.totpCode": "Код аутентификации",
	"auth.totpInvalid": "Неверный код аутентификации.",
	"a11y.skipToContent": "Перейти к основному содержимому",
	"a11y.breadcrumb": "Хлебные крошки",
	"a11y.dateDrilldown": "Навигация по дате",
	"a11y.select": "Выбрать",
	"a11y.selectRow": "Выбрать {name}",
	"a11y.sortBy": "Сортировать по {column}",
	"a11y.page": "Страница {n}",
	"a11y.viewItem": "Просмотреть {name}",
	"a11y.editItem": "Изменить {name}",
	"a11y.deleteItem": "Удалить {name}",
	"a11y.addItem": "Добавить {label}",
	"a11y.changeItem": "Изменить {label}",
	"a11y.deleteInlineRow": "Удалить эту строку",
	"nav.accounts": "Аккаунты",
	"accounts.users.singular": "пользователь",
	"accounts.users.title": "Пользователи",
	"accounts.users.empty": "Пользователи не найдены.",
	"accounts.users.col.username": "Имя пользователя",
	"accounts.users.col.label": "Метка",
	"accounts.users.col.active": "Активен",
	"accounts.users.col.superuser": "Суперпользователь",
	"accounts.users.col.lastLogin": "Последний вход",
	"accounts.users.newTitle": "Создать пользователя",
	"accounts.users.editTitle": "Изменить пользователя",
	"accounts.users.field.username": "Имя пользователя",
	"accounts.users.field.password": "Пароль",
	"accounts.users.field.newPassword": "Новый пароль",
	"accounts.users.field.label": "Метка",
	"accounts.users.field.active": "Активен",
	"accounts.users.field.superuser": "Суперпользователь",
	"accounts.users.field.permissions": "Права доступа",
	"accounts.users.field.groups": "Группы",
	"accounts.users.unknownPermissions": "Также сохраняются следующие нераспознанные права: {list}",
	"accounts.users.changePassword": "Изменить пароль",
	"accounts.users.lastActiveSuperuserError":
		"Невозможно деактивировать, понизить в правах или удалить последнего активного суперпользователя.",
	"accounts.users.saveError": "Не удалось сохранить: {detail}",
	"accounts.users.groupsLink": "Группы",
	"accounts.groups.singular": "группа",
	"accounts.groups.title": "Группы",
	"accounts.groups.empty": "Группы не найдены.",
	"accounts.groups.col.name": "Имя",
	"accounts.groups.col.permissionCount": "Права",
	"accounts.groups.usersLink": "Пользователи",
	"accounts.groups.newTitle": "Создать группу",
	"accounts.groups.editTitle": "Изменить группу",
	"accounts.groups.field.name": "Имя",
	"accounts.groups.field.permissions": "Права доступа",
	"accounts.groups.unknownPermissions": "Также сохраняются следующие нераспознанные права: {list}",
	"accounts.groups.saveError": "Не удалось сохранить: {detail}",
} satisfies AdminCatalog;

/** Korean catalog. */
const ko = {
	"nav.dashboard": "대시보드",
	"nav.jobs": "작업",
	"nav.settings": "설정",
	"nav.audit": "감사 로그",
	"dashboard.welcome": "환영합니다",
	"dashboard.empty": "아직 연결된 섹션이 없습니다.",
	"breadcrumb.home": "홈",
	"index.resources": "리소스",
	"action.add": "추가",
	"action.change": "변경",
	"action.filter": "필터",
	"filter.title": "필터",
	"filter.all": "전체",
	"action.search": "검색",
	"action.delete": "삭제",
	"action.actionLabel": "작업:",
	"action.run": "실행",
	"action.deleteSelected": "선택한 {label} 삭제",
	"action.edit": "편집",
	"action.detail": "상세",
	"action.save": "저장",
	"action.saveAddAnother": "저장 후 다른 항목 추가",
	"action.saveContinue": "저장 후 편집 계속",
	"action.create": "새로 만들기",
	"action.exportCsv": "CSV 내보내기",
	"action.retry": "재시도",
	"action.backToList": "목록으로",
	"action.next": "다음",
	"col.name": "이름",
	"jobs.title": "작업 관리",
	"jobs.pending": "대기 중",
	"jobs.failed": "실패",
	"jobs.emptyPending": "대기 중인 작업이 없습니다.",
	"jobs.emptyFailed": "실패한 작업이 없습니다.",
	"jobs.col.priority": "우선순위",
	"jobs.col.runAt": "예약 시각",
	"jobs.col.attempts": "시도 횟수",
	"jobs.col.failedAt": "실패 시각",
	"jobs.col.error": "오류",
	"audit.empty": "감사 로그가 없습니다.",
	"audit.col.time": "시각",
	"audit.col.changes": "변경",
	"resource.empty": "레코드가 없습니다.",
	"resource.newTitle": "{label} 만들기",
	"resource.editTitle": "{label} 편집",
	"resource.showTitle": "{label} 상세",
	"message.added": "{label}이(가) 추가되었습니다.",
	"message.changed": "{label}이(가) 변경되었습니다.",
	"message.deleted": "{label}이(가) 삭제되었습니다.",
	"message.deletedCount": "{count}개의 {label}이(가) 삭제되었습니다.",
	"delete.confirm": "이 {label}을(를) 삭제하시겠습니까?",
	"delete.confirmSelected": "선택한 {label}을(를) 삭제하시겠습니까?",
	"delete.yes": "예, 확실합니다",
	"delete.cancel": "아니요, 돌아가기",
	"settings.flags": "기능 플래그",
	"settings.flagsEmpty": "표시할 플래그가 없습니다.",
	"settings.enabled": "활성화됨",
	"settings.disabled": "비활성화됨",
	"settings.enable": "활성화",
	"settings.disable": "비활성화",
	"settings.maintenance": "유지보수 모드",
	"settings.current": "현재:",
	"settings.maintOn": "유지보수 중",
	"settings.maintOff": "정상 운영",
	"settings.maintEnable": "유지보수 시작",
	"settings.maintDisable": "유지보수 해제",
	"dateHierarchy.all": "모든 날짜",
	"auth.logIn": "로그인",
	"auth.logOut": "로그아웃",
	"auth.username": "사용자 이름",
	"auth.password": "비밀번호",
	"auth.invalid": "올바른 사용자 이름과 비밀번호를 입력하세요.",
	"auth.tooManyAttempts": "시도 횟수가 너무 많습니다. 나중에 다시 시도해 주세요.",
	"auth.totpTitle": "2단계 인증",
	"auth.totpCode": "인증 코드",
	"auth.totpInvalid": "인증 코드가 올바르지 않습니다.",
	"a11y.skipToContent": "본문으로 건너뛰기",
	"a11y.breadcrumb": "이동 경로",
	"a11y.dateDrilldown": "날짜별 탐색",
	"a11y.select": "선택",
	"a11y.selectRow": "{name} 선택",
	"a11y.sortBy": "{column} 기준 정렬",
	"a11y.page": "{n} 페이지",
	"a11y.viewItem": "{name} 보기",
	"a11y.editItem": "{name} 편집",
	"a11y.deleteItem": "{name} 삭제",
	"a11y.addItem": "{label} 추가",
	"a11y.changeItem": "{label} 변경",
	"a11y.deleteInlineRow": "이 행 삭제",
	"nav.accounts": "계정",
	"accounts.users.singular": "사용자",
	"accounts.users.title": "사용자",
	"accounts.users.empty": "사용자를 찾을 수 없습니다.",
	"accounts.users.col.username": "사용자 이름",
	"accounts.users.col.label": "라벨",
	"accounts.users.col.active": "활성",
	"accounts.users.col.superuser": "슈퍼유저",
	"accounts.users.col.lastLogin": "마지막 로그인",
	"accounts.users.newTitle": "사용자 만들기",
	"accounts.users.editTitle": "사용자 편집",
	"accounts.users.field.username": "사용자 이름",
	"accounts.users.field.password": "비밀번호",
	"accounts.users.field.newPassword": "새 비밀번호",
	"accounts.users.field.label": "라벨",
	"accounts.users.field.active": "활성",
	"accounts.users.field.superuser": "슈퍼유저",
	"accounts.users.field.permissions": "권한",
	"accounts.users.field.groups": "그룹",
	"accounts.users.unknownPermissions": "인식할 수 없는 다음 권한도 유지됩니다: {list}",
	"accounts.users.changePassword": "비밀번호 변경",
	"accounts.users.lastActiveSuperuserError":
		"마지막으로 남은 활성 슈퍼유저는 비활성화, 강등 또는 삭제할 수 없습니다.",
	"accounts.users.saveError": "저장할 수 없습니다: {detail}",
	"accounts.users.groupsLink": "그룹",
	"accounts.groups.singular": "그룹",
	"accounts.groups.title": "그룹",
	"accounts.groups.empty": "그룹을 찾을 수 없습니다.",
	"accounts.groups.col.name": "이름",
	"accounts.groups.col.permissionCount": "권한 수",
	"accounts.groups.usersLink": "사용자",
	"accounts.groups.newTitle": "그룹 만들기",
	"accounts.groups.editTitle": "그룹 편집",
	"accounts.groups.field.name": "이름",
	"accounts.groups.field.permissions": "권한",
	"accounts.groups.unknownPermissions": "인식할 수 없는 다음 권한도 유지됩니다: {list}",
	"accounts.groups.saveError": "저장할 수 없습니다: {detail}",
} satisfies AdminCatalog;

/** Arabic catalog (right-to-left). */
const ar = {
	"nav.dashboard": "لوحة التحكم",
	"nav.jobs": "المهام",
	"nav.settings": "الإعدادات",
	"nav.audit": "سجل التدقيق",
	"dashboard.welcome": "مرحبًا",
	"dashboard.empty": "لم يتم إعداد أي أقسام بعد.",
	"breadcrumb.home": "الرئيسية",
	"index.resources": "الموارد",
	"action.add": "إضافة",
	"action.change": "تعديل",
	"action.filter": "تصفية",
	"filter.title": "تصفية",
	"filter.all": "الكل",
	"action.search": "بحث",
	"action.delete": "حذف",
	"action.actionLabel": "الإجراء:",
	"action.run": "تنفيذ",
	"action.deleteSelected": "حذف {label} المحددة",
	"action.edit": "تعديل",
	"action.detail": "التفاصيل",
	"action.save": "حفظ",
	"action.saveAddAnother": "حفظ وإضافة آخر",
	"action.saveContinue": "حفظ ومتابعة التعديل",
	"action.create": "جديد",
	"action.exportCsv": "تصدير CSV",
	"action.retry": "إعادة المحاولة",
	"action.backToList": "العودة إلى القائمة",
	"action.next": "التالي",
	"col.name": "الاسم",
	"jobs.title": "عمليات المهام",
	"jobs.pending": "قيد الانتظار",
	"jobs.failed": "فشلت",
	"jobs.emptyPending": "لا توجد مهام قيد الانتظار.",
	"jobs.emptyFailed": "لا توجد مهام فاشلة.",
	"jobs.col.priority": "الأولوية",
	"jobs.col.runAt": "مجدولة",
	"jobs.col.attempts": "المحاولات",
	"jobs.col.failedAt": "وقت الفشل",
	"jobs.col.error": "خطأ",
	"audit.empty": "لم يتم العثور على سجلات تدقيق.",
	"audit.col.time": "الوقت",
	"audit.col.changes": "التغييرات",
	"resource.empty": "لم يتم العثور على سجلات.",
	"resource.newTitle": "إنشاء {label}",
	"resource.editTitle": "تعديل {label}",
	"resource.showTitle": "تفاصيل {label}",
	"message.added": "تمت إضافة {label} بنجاح.",
	"message.changed": "تم تعديل {label} بنجاح.",
	"message.deleted": "تم حذف {label} بنجاح.",
	"message.deletedCount": "تم حذف {count} من {label} بنجاح.",
	"delete.confirm": "هل أنت متأكد أنك تريد حذف هذا {label}؟",
	"delete.confirmSelected": "هل أنت متأكد أنك تريد حذف {label} المحددة؟",
	"delete.yes": "نعم، أنا متأكد",
	"delete.cancel": "لا، عد بي",
	"settings.flags": "أعلام الميزات",
	"settings.flagsEmpty": "لا توجد أعلام للعرض.",
	"settings.enabled": "مُفعّل",
	"settings.disabled": "مُعطّل",
	"settings.enable": "تفعيل",
	"settings.disable": "تعطيل",
	"settings.maintenance": "وضع الصيانة",
	"settings.current": "الحالي:",
	"settings.maintOn": "قيد الصيانة",
	"settings.maintOff": "تعمل بشكل طبيعي",
	"settings.maintEnable": "بدء الصيانة",
	"settings.maintDisable": "إنهاء الصيانة",
	"dateHierarchy.all": "كل التواريخ",
	"auth.logIn": "تسجيل الدخول",
	"auth.logOut": "تسجيل الخروج",
	"auth.username": "اسم المستخدم",
	"auth.password": "كلمة المرور",
	"auth.invalid": "يرجى إدخال اسم مستخدم وكلمة مرور صحيحين.",
	"auth.tooManyAttempts": "عدد كبير جدًا من المحاولات. حاول مرة أخرى لاحقًا.",
	"auth.totpTitle": "المصادقة الثنائية",
	"auth.totpCode": "رمز المصادقة",
	"auth.totpInvalid": "رمز مصادقة غير صالح.",
	"a11y.skipToContent": "تخطَّ إلى المحتوى الرئيسي",
	"a11y.breadcrumb": "مسار التنقل",
	"a11y.dateDrilldown": "التنقل حسب التاريخ",
	"a11y.select": "تحديد",
	"a11y.selectRow": "تحديد {name}",
	"a11y.sortBy": "الترتيب حسب {column}",
	"a11y.page": "الصفحة {n}",
	"a11y.viewItem": "عرض {name}",
	"a11y.editItem": "تعديل {name}",
	"a11y.deleteItem": "حذف {name}",
	"a11y.addItem": "إضافة {label}",
	"a11y.changeItem": "تعديل {label}",
	"a11y.deleteInlineRow": "حذف هذا الصف",
	"nav.accounts": "الحسابات",
	"accounts.users.singular": "مستخدم",
	"accounts.users.title": "المستخدمون",
	"accounts.users.empty": "لم يتم العثور على مستخدمين.",
	"accounts.users.col.username": "اسم المستخدم",
	"accounts.users.col.label": "التسمية",
	"accounts.users.col.active": "نشط",
	"accounts.users.col.superuser": "مستخدم مميز",
	"accounts.users.col.lastLogin": "آخر تسجيل دخول",
	"accounts.users.newTitle": "إنشاء مستخدم",
	"accounts.users.editTitle": "تعديل المستخدم",
	"accounts.users.field.username": "اسم المستخدم",
	"accounts.users.field.password": "كلمة المرور",
	"accounts.users.field.newPassword": "كلمة مرور جديدة",
	"accounts.users.field.label": "التسمية",
	"accounts.users.field.active": "نشط",
	"accounts.users.field.superuser": "مستخدم مميز",
	"accounts.users.field.permissions": "الصلاحيات",
	"accounts.users.field.groups": "المجموعات",
	"accounts.users.unknownPermissions": "يحتفظ أيضًا بهذه الصلاحيات غير المعروفة: {list}",
	"accounts.users.changePassword": "تغيير كلمة المرور",
	"accounts.users.lastActiveSuperuserError":
		"لا يمكن إلغاء تنشيط آخر مستخدم مميز نشط أو تخفيض رتبته أو حذفه.",
	"accounts.users.saveError": "تعذر الحفظ: {detail}",
	"accounts.users.groupsLink": "المجموعات",
	"accounts.groups.singular": "مجموعة",
	"accounts.groups.title": "المجموعات",
	"accounts.groups.empty": "لم يتم العثور على مجموعات.",
	"accounts.groups.col.name": "الاسم",
	"accounts.groups.col.permissionCount": "الصلاحيات",
	"accounts.groups.usersLink": "المستخدمون",
	"accounts.groups.newTitle": "إنشاء مجموعة",
	"accounts.groups.editTitle": "تعديل المجموعة",
	"accounts.groups.field.name": "الاسم",
	"accounts.groups.field.permissions": "الصلاحيات",
	"accounts.groups.unknownPermissions": "يحتفظ أيضًا بهذه الصلاحيات غير المعروفة: {list}",
	"accounts.groups.saveError": "تعذر الحفظ: {detail}",
} satisfies AdminCatalog;

/**
 * The admin panel's catalog bundle. `en` is the default/fallback; `ja`, `zh`, `es`,
 * `fr`, `de`, `pt`, `ru`, `ko`, and `ar` are matched against `c.get("language")`
 * (two-letter base codes, to maximize matches from `languageDetector`).
 */
export const adminCatalogBundle: CatalogBundle<AdminCatalog> = {
	en,
	ja,
	zh,
	es,
	fr,
	de,
	pt,
	ru,
	ko,
	ar,
};

/** The admin panel's translator, falling back to `en` when the detected language isn't in the bundle. */
export const adminTranslator = new Translator(adminCatalogBundle, { fallbackLanguage: "en" });

/**
 * The type of the bound translation function views receive as the `t` prop:
 * `Context` is already captured, so callers only pass `key` (and optional
 * interpolation `params`).
 */
export type AdminT = (key: keyof AdminCatalog, params?: TranslateParams) => string;

/** Builds an `AdminT` bound to `c`, so admin views can call `t(key)` without threading `Context` through. */
export const bindAdminT =
	(c: Context): AdminT =>
	(key, params) =>
		adminTranslator.t(c, key, params);
