/**
 * Message catalog for the unified admin panel's own UI labels (nav items, section
 * headings, action buttons, table column headers, etc.). This reuses the generic
 * `Translator`/`Catalog`/`CatalogBundle` machinery from `i18n/i18n.ts` (that module's
 * own `ja`/`en` catalog only covers framework-wide error pages; this is a separate,
 * admin-scoped catalog built the same way, per that module's doc comment inviting
 * apps to build their own catalogs).
 *
 * Scope: only labels the admin panel itself renders (dashboard/nav/jobs/settings/
 * audit/resource-CRUD chrome). Values the app supplies at runtime — `resource.label`,
 * `brand`, feature flag names, job `name`/`lastError`, audit `actor`/`action`/`target`,
 * and column names from `AdminResource#columns()` — are never translated here; they
 * are rendered as-is by the views regardless of the resolved language.
 *
 * Only `en` (default/fallback) and `ja` are implemented for now. Adding more
 * languages later is just adding more entries to `adminCatalogBundle` with the same
 * key set as `AdminCatalog`.
 */
import type { Context } from "hono";
import type { Catalog, CatalogBundle, TranslateParams } from "../i18n/i18n.js";
import { Translator } from "../i18n/i18n.js";

/** English catalog (default and fallback language for the admin panel). */
const en = {
	"nav.dashboard": "Dashboard",
	"nav.jobs": "Jobs",
	"nav.settings": "Settings",
	"nav.audit": "Audit log",
	"dashboard.welcome": "Welcome",
	"dashboard.empty": "No sections are wired up yet.",
	"action.filter": "Filter",
	"action.search": "Search",
	"action.delete": "Delete",
	"action.edit": "Edit",
	"action.detail": "Details",
	"action.save": "Save",
	"action.create": "New",
	"action.retry": "Retry",
	"action.backToList": "Back to list",
	"action.next": "Next",
	"col.name": "Name",
	"jobs.title": "Job operations",
	"jobs.pending": "Pending",
	"jobs.failed": "Failed",
	"jobs.emptyPending": "No pending jobs.",
	"jobs.emptyFailed": "No failed jobs.",
	"jobs.col.priority": "Priority",
	"jobs.col.runAt": "Scheduled",
	"jobs.col.attempts": "Attempts",
	"jobs.col.failedAt": "Failed at",
	"jobs.col.error": "Error",
	"audit.empty": "No audit logs found.",
	"audit.col.time": "Time",
	"audit.col.changes": "Changes",
	"resource.empty": "No records found.",
	"resource.newTitle": "Create {label}",
	"resource.editTitle": "Edit {label}",
	"resource.showTitle": "{label} details",
	"settings.flags": "Feature flags",
	"settings.flagsEmpty": "No flags to display.",
	"settings.enabled": "Enabled",
	"settings.disabled": "Disabled",
	"settings.enable": "Enable",
	"settings.disable": "Disable",
	"settings.maintenance": "Maintenance mode",
	"settings.current": "Current:",
	"settings.maintOn": "Under maintenance",
	"settings.maintOff": "Operating normally",
	"settings.maintEnable": "Start maintenance",
	"settings.maintDisable": "End maintenance",
} satisfies Catalog;

/** Japanese catalog. Values mirror the literals previously hard-coded in each `.tsx` view. */
const ja = {
	"nav.dashboard": "ダッシュボード",
	"nav.jobs": "ジョブ",
	"nav.settings": "設定",
	"nav.audit": "監査ログ",
	"dashboard.welcome": "ようこそ",
	"dashboard.empty": "配線済みの区画はまだありません。",
	"action.filter": "絞り込み",
	"action.search": "検索",
	"action.delete": "削除",
	"action.edit": "編集",
	"action.detail": "詳細",
	"action.save": "保存",
	"action.create": "新規作成",
	"action.retry": "再実行",
	"action.backToList": "一覧へ戻る",
	"action.next": "次へ",
	"col.name": "名前",
	"jobs.title": "ジョブ運用",
	"jobs.pending": "保留中",
	"jobs.failed": "失敗",
	"jobs.emptyPending": "保留中のジョブはありません",
	"jobs.emptyFailed": "失敗したジョブはありません",
	"jobs.col.priority": "優先度",
	"jobs.col.runAt": "実行予定",
	"jobs.col.attempts": "試行",
	"jobs.col.failedAt": "失敗時刻",
	"jobs.col.error": "エラー",
	"audit.empty": "該当する監査ログはありません",
	"audit.col.time": "時刻",
	"audit.col.changes": "変更",
	"resource.empty": "該当するレコードがありません",
	"resource.newTitle": "{label}（新規作成）",
	"resource.editTitle": "{label}（編集）",
	"resource.showTitle": "{label}（詳細）",
	"settings.flags": "フィーチャーフラグ",
	"settings.flagsEmpty": "表示対象のフラグはありません",
	"settings.enabled": "有効",
	"settings.disabled": "無効",
	"settings.enable": "有効化",
	"settings.disable": "無効化",
	"settings.maintenance": "メンテナンスモード",
	"settings.current": "現在:",
	"settings.maintOn": "メンテ中",
	"settings.maintOff": "通常運転",
	"settings.maintEnable": "メンテ開始",
	"settings.maintDisable": "メンテ解除",
} satisfies Catalog;

/** The key set of the admin panel's own catalog (`en` is authoritative; every other catalog mirrors the same keys). */
export type AdminCatalog = typeof en;

/** Simplified Chinese catalog. */
const zh = {
	"nav.dashboard": "仪表板",
	"nav.jobs": "任务",
	"nav.settings": "设置",
	"nav.audit": "审计日志",
	"dashboard.welcome": "欢迎",
	"dashboard.empty": "尚未接入任何模块。",
	"action.filter": "筛选",
	"action.search": "搜索",
	"action.delete": "删除",
	"action.edit": "编辑",
	"action.detail": "详情",
	"action.save": "保存",
	"action.create": "新建",
	"action.retry": "重试",
	"action.backToList": "返回列表",
	"action.next": "下一页",
	"col.name": "名称",
	"jobs.title": "任务管理",
	"jobs.pending": "待处理",
	"jobs.failed": "失败",
	"jobs.emptyPending": "没有待处理的任务。",
	"jobs.emptyFailed": "没有失败的任务。",
	"jobs.col.priority": "优先级",
	"jobs.col.runAt": "计划时间",
	"jobs.col.attempts": "尝试次数",
	"jobs.col.failedAt": "失败时间",
	"jobs.col.error": "错误",
	"audit.empty": "未找到审计日志。",
	"audit.col.time": "时间",
	"audit.col.changes": "变更",
	"resource.empty": "未找到记录。",
	"resource.newTitle": "新建{label}",
	"resource.editTitle": "编辑{label}",
	"resource.showTitle": "{label}详情",
	"settings.flags": "功能开关",
	"settings.flagsEmpty": "没有可显示的开关。",
	"settings.enabled": "已启用",
	"settings.disabled": "已禁用",
	"settings.enable": "启用",
	"settings.disable": "禁用",
	"settings.maintenance": "维护模式",
	"settings.current": "当前：",
	"settings.maintOn": "维护中",
	"settings.maintOff": "正常运行",
	"settings.maintEnable": "开启维护",
	"settings.maintDisable": "解除维护",
} satisfies AdminCatalog;

/** Spanish catalog. */
const es = {
	"nav.dashboard": "Panel",
	"nav.jobs": "Tareas",
	"nav.settings": "Configuración",
	"nav.audit": "Registro de auditoría",
	"dashboard.welcome": "Bienvenido",
	"dashboard.empty": "Aún no hay secciones configuradas.",
	"action.filter": "Filtrar",
	"action.search": "Buscar",
	"action.delete": "Eliminar",
	"action.edit": "Editar",
	"action.detail": "Detalles",
	"action.save": "Guardar",
	"action.create": "Nuevo",
	"action.retry": "Reintentar",
	"action.backToList": "Volver a la lista",
	"action.next": "Siguiente",
	"col.name": "Nombre",
	"jobs.title": "Operaciones de tareas",
	"jobs.pending": "Pendientes",
	"jobs.failed": "Fallidas",
	"jobs.emptyPending": "No hay tareas pendientes.",
	"jobs.emptyFailed": "No hay tareas fallidas.",
	"jobs.col.priority": "Prioridad",
	"jobs.col.runAt": "Programada",
	"jobs.col.attempts": "Intentos",
	"jobs.col.failedAt": "Fecha de fallo",
	"jobs.col.error": "Error",
	"audit.empty": "No se encontraron registros de auditoría.",
	"audit.col.time": "Hora",
	"audit.col.changes": "Cambios",
	"resource.empty": "No se encontraron registros.",
	"resource.newTitle": "Crear {label}",
	"resource.editTitle": "Editar {label}",
	"resource.showTitle": "Detalles de {label}",
	"settings.flags": "Indicadores de funciones",
	"settings.flagsEmpty": "No hay indicadores para mostrar.",
	"settings.enabled": "Habilitado",
	"settings.disabled": "Deshabilitado",
	"settings.enable": "Habilitar",
	"settings.disable": "Deshabilitar",
	"settings.maintenance": "Modo de mantenimiento",
	"settings.current": "Actual:",
	"settings.maintOn": "En mantenimiento",
	"settings.maintOff": "Funcionamiento normal",
	"settings.maintEnable": "Iniciar mantenimiento",
	"settings.maintDisable": "Finalizar mantenimiento",
} satisfies AdminCatalog;

/** French catalog. */
const fr = {
	"nav.dashboard": "Tableau de bord",
	"nav.jobs": "Tâches",
	"nav.settings": "Paramètres",
	"nav.audit": "Journal d'audit",
	"dashboard.welcome": "Bienvenue",
	"dashboard.empty": "Aucune section n'est encore configurée.",
	"action.filter": "Filtrer",
	"action.search": "Rechercher",
	"action.delete": "Supprimer",
	"action.edit": "Modifier",
	"action.detail": "Détails",
	"action.save": "Enregistrer",
	"action.create": "Nouveau",
	"action.retry": "Réessayer",
	"action.backToList": "Retour à la liste",
	"action.next": "Suivant",
	"col.name": "Nom",
	"jobs.title": "Gestion des tâches",
	"jobs.pending": "En attente",
	"jobs.failed": "Échouées",
	"jobs.emptyPending": "Aucune tâche en attente.",
	"jobs.emptyFailed": "Aucune tâche échouée.",
	"jobs.col.priority": "Priorité",
	"jobs.col.runAt": "Planifiée",
	"jobs.col.attempts": "Tentatives",
	"jobs.col.failedAt": "Date d'échec",
	"jobs.col.error": "Erreur",
	"audit.empty": "Aucun journal d'audit trouvé.",
	"audit.col.time": "Heure",
	"audit.col.changes": "Modifications",
	"resource.empty": "Aucun enregistrement trouvé.",
	"resource.newTitle": "Créer {label}",
	"resource.editTitle": "Modifier {label}",
	"resource.showTitle": "Détails de {label}",
	"settings.flags": "Indicateurs de fonctionnalités",
	"settings.flagsEmpty": "Aucun indicateur à afficher.",
	"settings.enabled": "Activé",
	"settings.disabled": "Désactivé",
	"settings.enable": "Activer",
	"settings.disable": "Désactiver",
	"settings.maintenance": "Mode maintenance",
	"settings.current": "Actuel :",
	"settings.maintOn": "En maintenance",
	"settings.maintOff": "Fonctionnement normal",
	"settings.maintEnable": "Démarrer la maintenance",
	"settings.maintDisable": "Terminer la maintenance",
} satisfies AdminCatalog;

/** German catalog. */
const de = {
	"nav.dashboard": "Dashboard",
	"nav.jobs": "Aufgaben",
	"nav.settings": "Einstellungen",
	"nav.audit": "Audit-Protokoll",
	"dashboard.welcome": "Willkommen",
	"dashboard.empty": "Es sind noch keine Bereiche eingerichtet.",
	"action.filter": "Filtern",
	"action.search": "Suchen",
	"action.delete": "Löschen",
	"action.edit": "Bearbeiten",
	"action.detail": "Details",
	"action.save": "Speichern",
	"action.create": "Neu",
	"action.retry": "Wiederholen",
	"action.backToList": "Zurück zur Liste",
	"action.next": "Weiter",
	"col.name": "Name",
	"jobs.title": "Aufgabenverwaltung",
	"jobs.pending": "Ausstehend",
	"jobs.failed": "Fehlgeschlagen",
	"jobs.emptyPending": "Keine ausstehenden Aufgaben.",
	"jobs.emptyFailed": "Keine fehlgeschlagenen Aufgaben.",
	"jobs.col.priority": "Priorität",
	"jobs.col.runAt": "Geplant",
	"jobs.col.attempts": "Versuche",
	"jobs.col.failedAt": "Fehlgeschlagen am",
	"jobs.col.error": "Fehler",
	"audit.empty": "Keine Audit-Protokolle gefunden.",
	"audit.col.time": "Zeit",
	"audit.col.changes": "Änderungen",
	"resource.empty": "Keine Datensätze gefunden.",
	"resource.newTitle": "{label} erstellen",
	"resource.editTitle": "{label} bearbeiten",
	"resource.showTitle": "Details zu {label}",
	"settings.flags": "Feature-Flags",
	"settings.flagsEmpty": "Keine Flags zum Anzeigen.",
	"settings.enabled": "Aktiviert",
	"settings.disabled": "Deaktiviert",
	"settings.enable": "Aktivieren",
	"settings.disable": "Deaktivieren",
	"settings.maintenance": "Wartungsmodus",
	"settings.current": "Aktuell:",
	"settings.maintOn": "In Wartung",
	"settings.maintOff": "Normalbetrieb",
	"settings.maintEnable": "Wartung starten",
	"settings.maintDisable": "Wartung beenden",
} satisfies AdminCatalog;

/** Brazilian Portuguese catalog. */
const pt = {
	"nav.dashboard": "Painel",
	"nav.jobs": "Tarefas",
	"nav.settings": "Configurações",
	"nav.audit": "Registro de auditoria",
	"dashboard.welcome": "Bem-vindo",
	"dashboard.empty": "Nenhuma seção configurada ainda.",
	"action.filter": "Filtrar",
	"action.search": "Buscar",
	"action.delete": "Excluir",
	"action.edit": "Editar",
	"action.detail": "Detalhes",
	"action.save": "Salvar",
	"action.create": "Novo",
	"action.retry": "Tentar novamente",
	"action.backToList": "Voltar à lista",
	"action.next": "Próximo",
	"col.name": "Nome",
	"jobs.title": "Operações de tarefas",
	"jobs.pending": "Pendentes",
	"jobs.failed": "Com falha",
	"jobs.emptyPending": "Nenhuma tarefa pendente.",
	"jobs.emptyFailed": "Nenhuma tarefa com falha.",
	"jobs.col.priority": "Prioridade",
	"jobs.col.runAt": "Agendada",
	"jobs.col.attempts": "Tentativas",
	"jobs.col.failedAt": "Falhou em",
	"jobs.col.error": "Erro",
	"audit.empty": "Nenhum registro de auditoria encontrado.",
	"audit.col.time": "Horário",
	"audit.col.changes": "Alterações",
	"resource.empty": "Nenhum registro encontrado.",
	"resource.newTitle": "Criar {label}",
	"resource.editTitle": "Editar {label}",
	"resource.showTitle": "Detalhes de {label}",
	"settings.flags": "Feature flags",
	"settings.flagsEmpty": "Nenhuma flag para exibir.",
	"settings.enabled": "Ativado",
	"settings.disabled": "Desativado",
	"settings.enable": "Ativar",
	"settings.disable": "Desativar",
	"settings.maintenance": "Modo de manutenção",
	"settings.current": "Atual:",
	"settings.maintOn": "Em manutenção",
	"settings.maintOff": "Operação normal",
	"settings.maintEnable": "Iniciar manutenção",
	"settings.maintDisable": "Encerrar manutenção",
} satisfies AdminCatalog;

/** Russian catalog. */
const ru = {
	"nav.dashboard": "Панель",
	"nav.jobs": "Задачи",
	"nav.settings": "Настройки",
	"nav.audit": "Журнал аудита",
	"dashboard.welcome": "Добро пожаловать",
	"dashboard.empty": "Разделы ещё не настроены.",
	"action.filter": "Фильтр",
	"action.search": "Поиск",
	"action.delete": "Удалить",
	"action.edit": "Изменить",
	"action.detail": "Подробности",
	"action.save": "Сохранить",
	"action.create": "Создать",
	"action.retry": "Повторить",
	"action.backToList": "Назад к списку",
	"action.next": "Далее",
	"col.name": "Имя",
	"jobs.title": "Управление задачами",
	"jobs.pending": "В ожидании",
	"jobs.failed": "Неуспешные",
	"jobs.emptyPending": "Нет ожидающих задач.",
	"jobs.emptyFailed": "Нет неуспешных задач.",
	"jobs.col.priority": "Приоритет",
	"jobs.col.runAt": "Запланировано",
	"jobs.col.attempts": "Попытки",
	"jobs.col.failedAt": "Время сбоя",
	"jobs.col.error": "Ошибка",
	"audit.empty": "Записи аудита не найдены.",
	"audit.col.time": "Время",
	"audit.col.changes": "Изменения",
	"resource.empty": "Записи не найдены.",
	"resource.newTitle": "Создать {label}",
	"resource.editTitle": "Изменить {label}",
	"resource.showTitle": "Подробности: {label}",
	"settings.flags": "Флаги функций",
	"settings.flagsEmpty": "Нет флагов для отображения.",
	"settings.enabled": "Включено",
	"settings.disabled": "Отключено",
	"settings.enable": "Включить",
	"settings.disable": "Отключить",
	"settings.maintenance": "Режим обслуживания",
	"settings.current": "Текущее:",
	"settings.maintOn": "На обслуживании",
	"settings.maintOff": "Работает нормально",
	"settings.maintEnable": "Начать обслуживание",
	"settings.maintDisable": "Завершить обслуживание",
} satisfies AdminCatalog;

/** Korean catalog. */
const ko = {
	"nav.dashboard": "대시보드",
	"nav.jobs": "작업",
	"nav.settings": "설정",
	"nav.audit": "감사 로그",
	"dashboard.welcome": "환영합니다",
	"dashboard.empty": "아직 연결된 섹션이 없습니다.",
	"action.filter": "필터",
	"action.search": "검색",
	"action.delete": "삭제",
	"action.edit": "편집",
	"action.detail": "상세",
	"action.save": "저장",
	"action.create": "새로 만들기",
	"action.retry": "재시도",
	"action.backToList": "목록으로",
	"action.next": "다음",
	"col.name": "이름",
	"jobs.title": "작업 관리",
	"jobs.pending": "대기 중",
	"jobs.failed": "실패",
	"jobs.emptyPending": "대기 중인 작업이 없습니다.",
	"jobs.emptyFailed": "실패한 작업이 없습니다.",
	"jobs.col.priority": "우선순위",
	"jobs.col.runAt": "예약 시각",
	"jobs.col.attempts": "시도 횟수",
	"jobs.col.failedAt": "실패 시각",
	"jobs.col.error": "오류",
	"audit.empty": "감사 로그가 없습니다.",
	"audit.col.time": "시각",
	"audit.col.changes": "변경",
	"resource.empty": "레코드가 없습니다.",
	"resource.newTitle": "{label} 만들기",
	"resource.editTitle": "{label} 편집",
	"resource.showTitle": "{label} 상세",
	"settings.flags": "기능 플래그",
	"settings.flagsEmpty": "표시할 플래그가 없습니다.",
	"settings.enabled": "활성화됨",
	"settings.disabled": "비활성화됨",
	"settings.enable": "활성화",
	"settings.disable": "비활성화",
	"settings.maintenance": "유지보수 모드",
	"settings.current": "현재:",
	"settings.maintOn": "유지보수 중",
	"settings.maintOff": "정상 운영",
	"settings.maintEnable": "유지보수 시작",
	"settings.maintDisable": "유지보수 해제",
} satisfies AdminCatalog;

/** Arabic catalog (right-to-left). */
const ar = {
	"nav.dashboard": "لوحة التحكم",
	"nav.jobs": "المهام",
	"nav.settings": "الإعدادات",
	"nav.audit": "سجل التدقيق",
	"dashboard.welcome": "مرحبًا",
	"dashboard.empty": "لم يتم إعداد أي أقسام بعد.",
	"action.filter": "تصفية",
	"action.search": "بحث",
	"action.delete": "حذف",
	"action.edit": "تعديل",
	"action.detail": "التفاصيل",
	"action.save": "حفظ",
	"action.create": "جديد",
	"action.retry": "إعادة المحاولة",
	"action.backToList": "العودة إلى القائمة",
	"action.next": "التالي",
	"col.name": "الاسم",
	"jobs.title": "عمليات المهام",
	"jobs.pending": "قيد الانتظار",
	"jobs.failed": "فشلت",
	"jobs.emptyPending": "لا توجد مهام قيد الانتظار.",
	"jobs.emptyFailed": "لا توجد مهام فاشلة.",
	"jobs.col.priority": "الأولوية",
	"jobs.col.runAt": "مجدولة",
	"jobs.col.attempts": "المحاولات",
	"jobs.col.failedAt": "وقت الفشل",
	"jobs.col.error": "خطأ",
	"audit.empty": "لم يتم العثور على سجلات تدقيق.",
	"audit.col.time": "الوقت",
	"audit.col.changes": "التغييرات",
	"resource.empty": "لم يتم العثور على سجلات.",
	"resource.newTitle": "إنشاء {label}",
	"resource.editTitle": "تعديل {label}",
	"resource.showTitle": "تفاصيل {label}",
	"settings.flags": "أعلام الميزات",
	"settings.flagsEmpty": "لا توجد أعلام للعرض.",
	"settings.enabled": "مُفعّل",
	"settings.disabled": "مُعطّل",
	"settings.enable": "تفعيل",
	"settings.disable": "تعطيل",
	"settings.maintenance": "وضع الصيانة",
	"settings.current": "الحالي:",
	"settings.maintOn": "قيد الصيانة",
	"settings.maintOff": "تعمل بشكل طبيعي",
	"settings.maintEnable": "بدء الصيانة",
	"settings.maintDisable": "إنهاء الصيانة",
} satisfies AdminCatalog;

/**
 * The admin panel's catalog bundle. `en` is the default/fallback; `ja`, `zh`, `es`,
 * `fr`, `de`, `pt`, `ru`, `ko`, and `ar` are matched against `c.get("language")`
 * (two-letter base codes, to maximize matches from `languageDetector`).
 */
export const adminCatalogBundle: CatalogBundle<AdminCatalog> = {
	en,
	ja,
	zh,
	es,
	fr,
	de,
	pt,
	ru,
	ko,
	ar,
};

/** The admin panel's translator, falling back to `en` when the detected language isn't in the bundle. */
export const adminTranslator = new Translator(adminCatalogBundle, { fallbackLanguage: "en" });

/**
 * The type of the bound translation function views receive as the `t` prop:
 * `Context` is already captured, so callers only pass `key` (and optional
 * interpolation `params`).
 */
export type AdminT = (key: keyof AdminCatalog, params?: TranslateParams) => string;

/** Builds an `AdminT` bound to `c`, so admin views can call `t(key)` without threading `Context` through. */
export const bindAdminT =
	(c: Context): AdminT =>
	(key, params) =>
		adminTranslator.t(c, key, params);
