/**
 * Message catalog for the unified admin panel's own UI labels (nav items, section
 * headings, action buttons, table column headers, etc.). This reuses the generic
 * `Translator`/`Catalog`/`CatalogBundle` machinery from `i18n/i18n.ts` (that module's
 * own `ja`/`en` catalog only covers framework-wide error pages; this is a separate,
 * admin-scoped catalog built the same way, per that module's doc comment inviting
 * apps to build their own catalogs).
 *
 * Scope: only labels the admin panel itself renders (dashboard/nav/jobs/settings/
 * audit/resource-CRUD chrome). Values the app supplies at runtime — `resource.label`,
 * `brand`, feature flag names, job `name`/`lastError`, audit `actor`/`action`/`target`,
 * and column names from `AdminResource#columns()` — are never translated here; they
 * are rendered as-is by the views regardless of the resolved language.
 *
 * Only `en` (default/fallback) and `ja` are implemented for now. Adding more
 * languages later is just adding more entries to `adminCatalogBundle` with the same
 * key set as `AdminCatalog`.
 */
import type { Context } from "hono";
import type { Catalog, CatalogBundle, TranslateParams } from "../i18n/i18n.js";
import { Translator } from "../i18n/i18n.js";

/** English catalog (default and fallback language for the admin panel). */
const en = {
	"nav.dashboard": "Dashboard",
	"nav.jobs": "Jobs",
	"nav.settings": "Settings",
	"nav.audit": "Audit log",
	"dashboard.welcome": "Welcome",
	"dashboard.empty": "No sections are wired up yet.",
	"breadcrumb.home": "Home",
	"index.resources": "Resources",
	"action.add": "Add",
	"action.change": "Change",
	"action.filter": "Filter",
	"filter.title": "Filter",
	"filter.all": "All",
	"action.search": "Search",
	"action.delete": "Delete",
	"action.actionLabel": "Action:",
	"action.run": "Run",
	"action.deleteSelected": "Delete selected {label}",
	"action.edit": "Edit",
	"action.detail": "Details",
	"action.save": "Save",
	"action.saveAddAnother": "Save and add another",
	"action.saveContinue": "Save and continue editing",
	"action.create": "New",
	"action.retry": "Retry",
	"action.backToList": "Back to list",
	"action.next": "Next",
	"col.name": "Name",
	"jobs.title": "Job operations",
	"jobs.pending": "Pending",
	"jobs.failed": "Failed",
	"jobs.emptyPending": "No pending jobs.",
	"jobs.emptyFailed": "No failed jobs.",
	"jobs.col.priority": "Priority",
	"jobs.col.runAt": "Scheduled",
	"jobs.col.attempts": "Attempts",
	"jobs.col.failedAt": "Failed at",
	"jobs.col.error": "Error",
	"audit.empty": "No audit logs found.",
	"audit.col.time": "Time",
	"audit.col.changes": "Changes",
	"resource.empty": "No records found.",
	"resource.newTitle": "Create {label}",
	"resource.editTitle": "Edit {label}",
	"resource.showTitle": "{label} details",
	"message.added": "The {label} was added successfully.",
	"message.changed": "The {label} was changed successfully.",
	"message.deleted": "The {label} was deleted successfully.",
	"message.deletedCount": "{count} {label} were deleted successfully.",
	"delete.confirm": "Are you sure you want to delete this {label}?",
	"delete.confirmSelected": "Are you sure you want to delete the selected {label}?",
	"delete.yes": "Yes, I'm sure",
	"delete.cancel": "No, take me back",
	"settings.flags": "Feature flags",
	"settings.flagsEmpty": "No flags to display.",
	"settings.enabled": "Enabled",
	"settings.disabled": "Disabled",
	"settings.enable": "Enable",
	"settings.disable": "Disable",
	"settings.maintenance": "Maintenance mode",
	"settings.current": "Current:",
	"settings.maintOn": "Under maintenance",
	"settings.maintOff": "Operating normally",
	"settings.maintEnable": "Start maintenance",
	"settings.maintDisable": "End maintenance",
	"dateHierarchy.all": "All dates",
	"auth.logIn": "Log in",
	"auth.logOut": "Log out",
	"auth.username": "Username",
	"auth.password": "Password",
	"auth.invalid": "Please enter a correct username and password.",
} satisfies Catalog;

/** Japanese catalog. Values mirror the literals previously hard-coded in each `.tsx` view. */
const ja = {
	"nav.dashboard": "ダッシュボード",
	"nav.jobs": "ジョブ",
	"nav.settings": "設定",
	"nav.audit": "監査ログ",
	"dashboard.welcome": "ようこそ",
	"dashboard.empty": "配線済みの区画はまだありません。",
	"breadcrumb.home": "ホーム",
	"index.resources": "リソース",
	"action.add": "追加",
	"action.change": "変更",
	"action.filter": "絞り込み",
	"filter.title": "絞り込み",
	"filter.all": "すべて",
	"action.search": "検索",
	"action.delete": "削除",
	"action.actionLabel": "アクション:",
	"action.run": "実行",
	"action.deleteSelected": "選択した {label} を削除",
	"action.edit": "編集",
	"action.detail": "詳細",
	"action.save": "保存",
	"action.saveAddAnother": "保存して続けて追加",
	"action.saveContinue": "保存して編集を続ける",
	"action.create": "新規作成",
	"action.retry": "再実行",
	"action.backToList": "一覧へ戻る",
	"action.next": "次へ",
	"col.name": "名前",
	"jobs.title": "ジョブ運用",
	"jobs.pending": "保留中",
	"jobs.failed": "失敗",
	"jobs.emptyPending": "保留中のジョブはありません",
	"jobs.emptyFailed": "失敗したジョブはありません",
	"jobs.col.priority": "優先度",
	"jobs.col.runAt": "実行予定",
	"jobs.col.attempts": "試行",
	"jobs.col.failedAt": "失敗時刻",
	"jobs.col.error": "エラー",
	"audit.empty": "該当する監査ログはありません",
	"audit.col.time": "時刻",
	"audit.col.changes": "変更",
	"resource.empty": "該当するレコードがありません",
	"resource.newTitle": "{label}（新規作成）",
	"resource.editTitle": "{label}（編集）",
	"resource.showTitle": "{label}（詳細）",
	"message.added": "{label} を追加しました。",
	"message.changed": "{label} を変更しました。",
	"message.deleted": "{label} を削除しました。",
	"message.deletedCount": "{count} 件の {label} を削除しました。",
	"delete.confirm": "この {label} を削除してもよろしいですか？",
	"delete.confirmSelected": "選択した {label} を削除してもよろしいですか？",
	"delete.yes": "はい、削除します",
	"delete.cancel": "いいえ、戻る",
	"settings.flags": "フィーチャーフラグ",
	"settings.flagsEmpty": "表示対象のフラグはありません",
	"settings.enabled": "有効",
	"settings.disabled": "無効",
	"settings.enable": "有効化",
	"settings.disable": "無効化",
	"settings.maintenance": "メンテナンスモード",
	"settings.current": "現在:",
	"settings.maintOn": "メンテ中",
	"settings.maintOff": "通常運転",
	"settings.maintEnable": "メンテ開始",
	"settings.maintDisable": "メンテ解除",
	"dateHierarchy.all": "すべての日付",
	"auth.logIn": "ログイン",
	"auth.logOut": "ログアウト",
	"auth.username": "ユーザー名",
	"auth.password": "パスワード",
	"auth.invalid": "正しいユーザー名とパスワードを入力してください。",
} satisfies Catalog;

/** The key set of the admin panel's own catalog (`en` is authoritative; every other catalog mirrors the same keys). */
export type AdminCatalog = typeof en;

/** Simplified Chinese catalog. */
const zh = {
	"nav.dashboard": "仪表板",
	"nav.jobs": "任务",
	"nav.settings": "设置",
	"nav.audit": "审计日志",
	"dashboard.welcome": "欢迎",
	"dashboard.empty": "尚未接入任何模块。",
	"breadcrumb.home": "首页",
	"index.resources": "资源",
	"action.add": "添加",
	"action.change": "修改",
	"action.filter": "筛选",
	"filter.title": "筛选",
	"filter.all": "全部",
	"action.search": "搜索",
	"action.delete": "删除",
	"action.actionLabel": "操作：",
	"action.run": "执行",
	"action.deleteSelected": "删除所选{label}",
	"action.edit": "编辑",
	"action.detail": "详情",
	"action.save": "保存",
	"action.saveAddAnother": "保存并新增",
	"action.saveContinue": "保存并继续编辑",
	"action.create": "新建",
	"action.retry": "重试",
	"action.backToList": "返回列表",
	"action.next": "下一页",
	"col.name": "名称",
	"jobs.title": "任务管理",
	"jobs.pending": "待处理",
	"jobs.failed": "失败",
	"jobs.emptyPending": "没有待处理的任务。",
	"jobs.emptyFailed": "没有失败的任务。",
	"jobs.col.priority": "优先级",
	"jobs.col.runAt": "计划时间",
	"jobs.col.attempts": "尝试次数",
	"jobs.col.failedAt": "失败时间",
	"jobs.col.error": "错误",
	"audit.empty": "未找到审计日志。",
	"audit.col.time": "时间",
	"audit.col.changes": "变更",
	"resource.empty": "未找到记录。",
	"resource.newTitle": "新建{label}",
	"resource.editTitle": "编辑{label}",
	"resource.showTitle": "{label}详情",
	"message.added": "{label} 添加成功。",
	"message.changed": "{label} 修改成功。",
	"message.deleted": "{label} 删除成功。",
	"message.deletedCount": "已成功删除 {count} 个{label}。",
	"delete.confirm": "确定要删除这个 {label} 吗？",
	"delete.confirmSelected": "确定要删除所选的 {label} 吗？",
	"delete.yes": "是的，我确定",
	"delete.cancel": "不，返回",
	"settings.flags": "功能开关",
	"settings.flagsEmpty": "没有可显示的开关。",
	"settings.enabled": "已启用",
	"settings.disabled": "已禁用",
	"settings.enable": "启用",
	"settings.disable": "禁用",
	"settings.maintenance": "维护模式",
	"settings.current": "当前：",
	"settings.maintOn": "维护中",
	"settings.maintOff": "正常运行",
	"settings.maintEnable": "开启维护",
	"settings.maintDisable": "解除维护",
	"dateHierarchy.all": "所有日期",
	"auth.logIn": "登录",
	"auth.logOut": "退出登录",
	"auth.username": "用户名",
	"auth.password": "密码",
	"auth.invalid": "请输入正确的用户名和密码。",
} satisfies AdminCatalog;

/** Spanish catalog. */
const es = {
	"nav.dashboard": "Panel",
	"nav.jobs": "Tareas",
	"nav.settings": "Configuración",
	"nav.audit": "Registro de auditoría",
	"dashboard.welcome": "Bienvenido",
	"dashboard.empty": "Aún no hay secciones configuradas.",
	"breadcrumb.home": "Inicio",
	"index.resources": "Recursos",
	"action.add": "Añadir",
	"action.change": "Editar",
	"action.filter": "Filtrar",
	"filter.title": "Filtro",
	"filter.all": "Todos",
	"action.search": "Buscar",
	"action.delete": "Eliminar",
	"action.actionLabel": "Acción:",
	"action.run": "Ejecutar",
	"action.deleteSelected": "Eliminar {label} seleccionados",
	"action.edit": "Editar",
	"action.detail": "Detalles",
	"action.save": "Guardar",
	"action.saveAddAnother": "Guardar y añadir otro",
	"action.saveContinue": "Guardar y continuar editando",
	"action.create": "Nuevo",
	"action.retry": "Reintentar",
	"action.backToList": "Volver a la lista",
	"action.next": "Siguiente",
	"col.name": "Nombre",
	"jobs.title": "Operaciones de tareas",
	"jobs.pending": "Pendientes",
	"jobs.failed": "Fallidas",
	"jobs.emptyPending": "No hay tareas pendientes.",
	"jobs.emptyFailed": "No hay tareas fallidas.",
	"jobs.col.priority": "Prioridad",
	"jobs.col.runAt": "Programada",
	"jobs.col.attempts": "Intentos",
	"jobs.col.failedAt": "Fecha de fallo",
	"jobs.col.error": "Error",
	"audit.empty": "No se encontraron registros de auditoría.",
	"audit.col.time": "Hora",
	"audit.col.changes": "Cambios",
	"resource.empty": "No se encontraron registros.",
	"resource.newTitle": "Crear {label}",
	"resource.editTitle": "Editar {label}",
	"resource.showTitle": "Detalles de {label}",
	"message.added": "El {label} se añadió correctamente.",
	"message.changed": "El {label} se modificó correctamente.",
	"message.deleted": "El {label} se eliminó correctamente.",
	"message.deletedCount": "Se eliminaron {count} {label} correctamente.",
	"delete.confirm": "¿Está seguro de que quiere eliminar este {label}?",
	"delete.confirmSelected": "¿Está seguro de que quiere eliminar los {label} seleccionados?",
	"delete.yes": "Sí, estoy seguro",
	"delete.cancel": "No, volver atrás",
	"settings.flags": "Indicadores de funciones",
	"settings.flagsEmpty": "No hay indicadores para mostrar.",
	"settings.enabled": "Habilitado",
	"settings.disabled": "Deshabilitado",
	"settings.enable": "Habilitar",
	"settings.disable": "Deshabilitar",
	"settings.maintenance": "Modo de mantenimiento",
	"settings.current": "Actual:",
	"settings.maintOn": "En mantenimiento",
	"settings.maintOff": "Funcionamiento normal",
	"settings.maintEnable": "Iniciar mantenimiento",
	"settings.maintDisable": "Finalizar mantenimiento",
	"dateHierarchy.all": "Todas las fechas",
	"auth.logIn": "Iniciar sesión",
	"auth.logOut": "Cerrar sesión",
	"auth.username": "Usuario",
	"auth.password": "Contraseña",
	"auth.invalid": "Introduzca un nombre de usuario y una contraseña correctos.",
} satisfies AdminCatalog;

/** French catalog. */
const fr = {
	"nav.dashboard": "Tableau de bord",
	"nav.jobs": "Tâches",
	"nav.settings": "Paramètres",
	"nav.audit": "Journal d'audit",
	"dashboard.welcome": "Bienvenue",
	"dashboard.empty": "Aucune section n'est encore configurée.",
	"breadcrumb.home": "Accueil",
	"index.resources": "Ressources",
	"action.add": "Ajouter",
	"action.change": "Modifier",
	"action.filter": "Filtrer",
	"filter.title": "Filtre",
	"filter.all": "Tous",
	"action.search": "Rechercher",
	"action.delete": "Supprimer",
	"action.actionLabel": "Action :",
	"action.run": "Exécuter",
	"action.deleteSelected": "Supprimer les {label} sélectionnés",
	"action.edit": "Modifier",
	"action.detail": "Détails",
	"action.save": "Enregistrer",
	"action.saveAddAnother": "Enregistrer et ajouter un autre",
	"action.saveContinue": "Enregistrer et continuer les modifications",
	"action.create": "Nouveau",
	"action.retry": "Réessayer",
	"action.backToList": "Retour à la liste",
	"action.next": "Suivant",
	"col.name": "Nom",
	"jobs.title": "Gestion des tâches",
	"jobs.pending": "En attente",
	"jobs.failed": "Échouées",
	"jobs.emptyPending": "Aucune tâche en attente.",
	"jobs.emptyFailed": "Aucune tâche échouée.",
	"jobs.col.priority": "Priorité",
	"jobs.col.runAt": "Planifiée",
	"jobs.col.attempts": "Tentatives",
	"jobs.col.failedAt": "Date d'échec",
	"jobs.col.error": "Erreur",
	"audit.empty": "Aucun journal d'audit trouvé.",
	"audit.col.time": "Heure",
	"audit.col.changes": "Modifications",
	"resource.empty": "Aucun enregistrement trouvé.",
	"resource.newTitle": "Créer {label}",
	"resource.editTitle": "Modifier {label}",
	"resource.showTitle": "Détails de {label}",
	"message.added": "Le {label} a été ajouté avec succès.",
	"message.changed": "Le {label} a été modifié avec succès.",
	"message.deleted": "Le {label} a été supprimé avec succès.",
	"message.deletedCount": "{count} {label} ont été supprimés avec succès.",
	"delete.confirm": "Êtes-vous sûr de vouloir supprimer ce {label} ?",
	"delete.confirmSelected": "Êtes-vous sûr de vouloir supprimer les {label} sélectionnés ?",
	"delete.yes": "Oui, je suis sûr",
	"delete.cancel": "Non, revenir en arrière",
	"settings.flags": "Indicateurs de fonctionnalités",
	"settings.flagsEmpty": "Aucun indicateur à afficher.",
	"settings.enabled": "Activé",
	"settings.disabled": "Désactivé",
	"settings.enable": "Activer",
	"settings.disable": "Désactiver",
	"settings.maintenance": "Mode maintenance",
	"settings.current": "Actuel :",
	"settings.maintOn": "En maintenance",
	"settings.maintOff": "Fonctionnement normal",
	"settings.maintEnable": "Démarrer la maintenance",
	"settings.maintDisable": "Terminer la maintenance",
	"dateHierarchy.all": "Toutes les dates",
	"auth.logIn": "Connexion",
	"auth.logOut": "Déconnexion",
	"auth.username": "Nom d'utilisateur",
	"auth.password": "Mot de passe",
	"auth.invalid": "Veuillez saisir un nom d'utilisateur et un mot de passe corrects.",
} satisfies AdminCatalog;

/** German catalog. */
const de = {
	"nav.dashboard": "Dashboard",
	"nav.jobs": "Aufgaben",
	"nav.settings": "Einstellungen",
	"nav.audit": "Audit-Protokoll",
	"dashboard.welcome": "Willkommen",
	"dashboard.empty": "Es sind noch keine Bereiche eingerichtet.",
	"breadcrumb.home": "Startseite",
	"index.resources": "Ressourcen",
	"action.add": "Hinzufügen",
	"action.change": "Ändern",
	"action.filter": "Filtern",
	"filter.title": "Filter",
	"filter.all": "Alle",
	"action.search": "Suchen",
	"action.delete": "Löschen",
	"action.actionLabel": "Aktion:",
	"action.run": "Ausführen",
	"action.deleteSelected": "Ausgewählte {label} löschen",
	"action.edit": "Bearbeiten",
	"action.detail": "Details",
	"action.save": "Speichern",
	"action.saveAddAnother": "Sichern und neu hinzufügen",
	"action.saveContinue": "Sichern und weiter bearbeiten",
	"action.create": "Neu",
	"action.retry": "Wiederholen",
	"action.backToList": "Zurück zur Liste",
	"action.next": "Weiter",
	"col.name": "Name",
	"jobs.title": "Aufgabenverwaltung",
	"jobs.pending": "Ausstehend",
	"jobs.failed": "Fehlgeschlagen",
	"jobs.emptyPending": "Keine ausstehenden Aufgaben.",
	"jobs.emptyFailed": "Keine fehlgeschlagenen Aufgaben.",
	"jobs.col.priority": "Priorität",
	"jobs.col.runAt": "Geplant",
	"jobs.col.attempts": "Versuche",
	"jobs.col.failedAt": "Fehlgeschlagen am",
	"jobs.col.error": "Fehler",
	"audit.empty": "Keine Audit-Protokolle gefunden.",
	"audit.col.time": "Zeit",
	"audit.col.changes": "Änderungen",
	"resource.empty": "Keine Datensätze gefunden.",
	"resource.newTitle": "{label} erstellen",
	"resource.editTitle": "{label} bearbeiten",
	"resource.showTitle": "Details zu {label}",
	"message.added": "Das {label} wurde erfolgreich hinzugefügt.",
	"message.changed": "Das {label} wurde erfolgreich geändert.",
	"message.deleted": "Das {label} wurde erfolgreich gelöscht.",
	"message.deletedCount": "{count} {label} wurden erfolgreich gelöscht.",
	"delete.confirm": "Sind Sie sicher, dass Sie dieses {label} löschen möchten?",
	"delete.confirmSelected": "Sind Sie sicher, dass Sie die ausgewählten {label} löschen möchten?",
	"delete.yes": "Ja, ich bin sicher",
	"delete.cancel": "Nein, zurück",
	"settings.flags": "Feature-Flags",
	"settings.flagsEmpty": "Keine Flags zum Anzeigen.",
	"settings.enabled": "Aktiviert",
	"settings.disabled": "Deaktiviert",
	"settings.enable": "Aktivieren",
	"settings.disable": "Deaktivieren",
	"settings.maintenance": "Wartungsmodus",
	"settings.current": "Aktuell:",
	"settings.maintOn": "In Wartung",
	"settings.maintOff": "Normalbetrieb",
	"settings.maintEnable": "Wartung starten",
	"settings.maintDisable": "Wartung beenden",
	"dateHierarchy.all": "Alle Daten",
	"auth.logIn": "Anmelden",
	"auth.logOut": "Abmelden",
	"auth.username": "Benutzername",
	"auth.password": "Passwort",
	"auth.invalid": "Bitte geben Sie einen korrekten Benutzernamen und ein korrektes Passwort ein.",
} satisfies AdminCatalog;

/** Brazilian Portuguese catalog. */
const pt = {
	"nav.dashboard": "Painel",
	"nav.jobs": "Tarefas",
	"nav.settings": "Configurações",
	"nav.audit": "Registro de auditoria",
	"dashboard.welcome": "Bem-vindo",
	"dashboard.empty": "Nenhuma seção configurada ainda.",
	"breadcrumb.home": "Início",
	"index.resources": "Recursos",
	"action.add": "Adicionar",
	"action.change": "Alterar",
	"action.filter": "Filtrar",
	"filter.title": "Filtro",
	"filter.all": "Todos",
	"action.search": "Buscar",
	"action.delete": "Excluir",
	"action.actionLabel": "Ação:",
	"action.run": "Executar",
	"action.deleteSelected": "Excluir {label} selecionados",
	"action.edit": "Editar",
	"action.detail": "Detalhes",
	"action.save": "Salvar",
	"action.saveAddAnother": "Salvar e adicionar outro",
	"action.saveContinue": "Salvar e continuar editando",
	"action.create": "Novo",
	"action.retry": "Tentar novamente",
	"action.backToList": "Voltar à lista",
	"action.next": "Próximo",
	"col.name": "Nome",
	"jobs.title": "Operações de tarefas",
	"jobs.pending": "Pendentes",
	"jobs.failed": "Com falha",
	"jobs.emptyPending": "Nenhuma tarefa pendente.",
	"jobs.emptyFailed": "Nenhuma tarefa com falha.",
	"jobs.col.priority": "Prioridade",
	"jobs.col.runAt": "Agendada",
	"jobs.col.attempts": "Tentativas",
	"jobs.col.failedAt": "Falhou em",
	"jobs.col.error": "Erro",
	"audit.empty": "Nenhum registro de auditoria encontrado.",
	"audit.col.time": "Horário",
	"audit.col.changes": "Alterações",
	"resource.empty": "Nenhum registro encontrado.",
	"resource.newTitle": "Criar {label}",
	"resource.editTitle": "Editar {label}",
	"resource.showTitle": "Detalhes de {label}",
	"message.added": "O {label} foi adicionado com sucesso.",
	"message.changed": "O {label} foi alterado com sucesso.",
	"message.deleted": "O {label} foi excluído com sucesso.",
	"message.deletedCount": "{count} {label} foram excluídos com sucesso.",
	"delete.confirm": "Tem certeza de que deseja excluir este {label}?",
	"delete.confirmSelected": "Tem certeza de que deseja excluir os {label} selecionados?",
	"delete.yes": "Sim, tenho certeza",
	"delete.cancel": "Não, voltar",
	"settings.flags": "Feature flags",
	"settings.flagsEmpty": "Nenhuma flag para exibir.",
	"settings.enabled": "Ativado",
	"settings.disabled": "Desativado",
	"settings.enable": "Ativar",
	"settings.disable": "Desativar",
	"settings.maintenance": "Modo de manutenção",
	"settings.current": "Atual:",
	"settings.maintOn": "Em manutenção",
	"settings.maintOff": "Operação normal",
	"settings.maintEnable": "Iniciar manutenção",
	"settings.maintDisable": "Encerrar manutenção",
	"dateHierarchy.all": "Todas as datas",
	"auth.logIn": "Entrar",
	"auth.logOut": "Sair",
	"auth.username": "Nome de usuário",
	"auth.password": "Senha",
	"auth.invalid": "Digite um nome de usuário e uma senha corretos.",
} satisfies AdminCatalog;

/** Russian catalog. */
const ru = {
	"nav.dashboard": "Панель",
	"nav.jobs": "Задачи",
	"nav.settings": "Настройки",
	"nav.audit": "Журнал аудита",
	"dashboard.welcome": "Добро пожаловать",
	"dashboard.empty": "Разделы ещё не настроены.",
	"breadcrumb.home": "Главная",
	"index.resources": "Ресурсы",
	"action.add": "Добавить",
	"action.change": "Изменить",
	"action.filter": "Фильтр",
	"filter.title": "Фильтр",
	"filter.all": "Все",
	"action.search": "Поиск",
	"action.delete": "Удалить",
	"action.actionLabel": "Действие:",
	"action.run": "Выполнить",
	"action.deleteSelected": "Удалить выбранные {label}",
	"action.edit": "Изменить",
	"action.detail": "Подробности",
	"action.save": "Сохранить",
	"action.saveAddAnother": "Сохранить и добавить другой объект",
	"action.saveContinue": "Сохранить и продолжить редактирование",
	"action.create": "Создать",
	"action.retry": "Повторить",
	"action.backToList": "Назад к списку",
	"action.next": "Далее",
	"col.name": "Имя",
	"jobs.title": "Управление задачами",
	"jobs.pending": "В ожидании",
	"jobs.failed": "Неуспешные",
	"jobs.emptyPending": "Нет ожидающих задач.",
	"jobs.emptyFailed": "Нет неуспешных задач.",
	"jobs.col.priority": "Приоритет",
	"jobs.col.runAt": "Запланировано",
	"jobs.col.attempts": "Попытки",
	"jobs.col.failedAt": "Время сбоя",
	"jobs.col.error": "Ошибка",
	"audit.empty": "Записи аудита не найдены.",
	"audit.col.time": "Время",
	"audit.col.changes": "Изменения",
	"resource.empty": "Записи не найдены.",
	"resource.newTitle": "Создать {label}",
	"resource.editTitle": "Изменить {label}",
	"resource.showTitle": "Подробности: {label}",
	"message.added": "{label} успешно добавлен.",
	"message.changed": "{label} успешно изменён.",
	"message.deleted": "{label} успешно удалён.",
	"message.deletedCount": "{count} {label} успешно удалено.",
	"delete.confirm": "Вы уверены, что хотите удалить этот {label}?",
	"delete.confirmSelected": "Вы уверены, что хотите удалить выбранные {label}?",
	"delete.yes": "Да, я уверен",
	"delete.cancel": "Нет, вернуться назад",
	"settings.flags": "Флаги функций",
	"settings.flagsEmpty": "Нет флагов для отображения.",
	"settings.enabled": "Включено",
	"settings.disabled": "Отключено",
	"settings.enable": "Включить",
	"settings.disable": "Отключить",
	"settings.maintenance": "Режим обслуживания",
	"settings.current": "Текущее:",
	"settings.maintOn": "На обслуживании",
	"settings.maintOff": "Работает нормально",
	"settings.maintEnable": "Начать обслуживание",
	"settings.maintDisable": "Завершить обслуживание",
	"dateHierarchy.all": "Все даты",
	"auth.logIn": "Войти",
	"auth.logOut": "Выйти",
	"auth.username": "Имя пользователя",
	"auth.password": "Пароль",
	"auth.invalid": "Пожалуйста, введите правильные имя пользователя и пароль.",
} satisfies AdminCatalog;

/** Korean catalog. */
const ko = {
	"nav.dashboard": "대시보드",
	"nav.jobs": "작업",
	"nav.settings": "설정",
	"nav.audit": "감사 로그",
	"dashboard.welcome": "환영합니다",
	"dashboard.empty": "아직 연결된 섹션이 없습니다.",
	"breadcrumb.home": "홈",
	"index.resources": "리소스",
	"action.add": "추가",
	"action.change": "변경",
	"action.filter": "필터",
	"filter.title": "필터",
	"filter.all": "전체",
	"action.search": "검색",
	"action.delete": "삭제",
	"action.actionLabel": "작업:",
	"action.run": "실행",
	"action.deleteSelected": "선택한 {label} 삭제",
	"action.edit": "편집",
	"action.detail": "상세",
	"action.save": "저장",
	"action.saveAddAnother": "저장 후 다른 항목 추가",
	"action.saveContinue": "저장 후 편집 계속",
	"action.create": "새로 만들기",
	"action.retry": "재시도",
	"action.backToList": "목록으로",
	"action.next": "다음",
	"col.name": "이름",
	"jobs.title": "작업 관리",
	"jobs.pending": "대기 중",
	"jobs.failed": "실패",
	"jobs.emptyPending": "대기 중인 작업이 없습니다.",
	"jobs.emptyFailed": "실패한 작업이 없습니다.",
	"jobs.col.priority": "우선순위",
	"jobs.col.runAt": "예약 시각",
	"jobs.col.attempts": "시도 횟수",
	"jobs.col.failedAt": "실패 시각",
	"jobs.col.error": "오류",
	"audit.empty": "감사 로그가 없습니다.",
	"audit.col.time": "시각",
	"audit.col.changes": "변경",
	"resource.empty": "레코드가 없습니다.",
	"resource.newTitle": "{label} 만들기",
	"resource.editTitle": "{label} 편집",
	"resource.showTitle": "{label} 상세",
	"message.added": "{label}이(가) 추가되었습니다.",
	"message.changed": "{label}이(가) 변경되었습니다.",
	"message.deleted": "{label}이(가) 삭제되었습니다.",
	"message.deletedCount": "{count}개의 {label}이(가) 삭제되었습니다.",
	"delete.confirm": "이 {label}을(를) 삭제하시겠습니까?",
	"delete.confirmSelected": "선택한 {label}을(를) 삭제하시겠습니까?",
	"delete.yes": "예, 확실합니다",
	"delete.cancel": "아니요, 돌아가기",
	"settings.flags": "기능 플래그",
	"settings.flagsEmpty": "표시할 플래그가 없습니다.",
	"settings.enabled": "활성화됨",
	"settings.disabled": "비활성화됨",
	"settings.enable": "활성화",
	"settings.disable": "비활성화",
	"settings.maintenance": "유지보수 모드",
	"settings.current": "현재:",
	"settings.maintOn": "유지보수 중",
	"settings.maintOff": "정상 운영",
	"settings.maintEnable": "유지보수 시작",
	"settings.maintDisable": "유지보수 해제",
	"dateHierarchy.all": "모든 날짜",
	"auth.logIn": "로그인",
	"auth.logOut": "로그아웃",
	"auth.username": "사용자 이름",
	"auth.password": "비밀번호",
	"auth.invalid": "올바른 사용자 이름과 비밀번호를 입력하세요.",
} satisfies AdminCatalog;

/** Arabic catalog (right-to-left). */
const ar = {
	"nav.dashboard": "لوحة التحكم",
	"nav.jobs": "المهام",
	"nav.settings": "الإعدادات",
	"nav.audit": "سجل التدقيق",
	"dashboard.welcome": "مرحبًا",
	"dashboard.empty": "لم يتم إعداد أي أقسام بعد.",
	"breadcrumb.home": "الرئيسية",
	"index.resources": "الموارد",
	"action.add": "إضافة",
	"action.change": "تعديل",
	"action.filter": "تصفية",
	"filter.title": "تصفية",
	"filter.all": "الكل",
	"action.search": "بحث",
	"action.delete": "حذف",
	"action.actionLabel": "الإجراء:",
	"action.run": "تنفيذ",
	"action.deleteSelected": "حذف {label} المحددة",
	"action.edit": "تعديل",
	"action.detail": "التفاصيل",
	"action.save": "حفظ",
	"action.saveAddAnother": "حفظ وإضافة آخر",
	"action.saveContinue": "حفظ ومتابعة التعديل",
	"action.create": "جديد",
	"action.retry": "إعادة المحاولة",
	"action.backToList": "العودة إلى القائمة",
	"action.next": "التالي",
	"col.name": "الاسم",
	"jobs.title": "عمليات المهام",
	"jobs.pending": "قيد الانتظار",
	"jobs.failed": "فشلت",
	"jobs.emptyPending": "لا توجد مهام قيد الانتظار.",
	"jobs.emptyFailed": "لا توجد مهام فاشلة.",
	"jobs.col.priority": "الأولوية",
	"jobs.col.runAt": "مجدولة",
	"jobs.col.attempts": "المحاولات",
	"jobs.col.failedAt": "وقت الفشل",
	"jobs.col.error": "خطأ",
	"audit.empty": "لم يتم العثور على سجلات تدقيق.",
	"audit.col.time": "الوقت",
	"audit.col.changes": "التغييرات",
	"resource.empty": "لم يتم العثور على سجلات.",
	"resource.newTitle": "إنشاء {label}",
	"resource.editTitle": "تعديل {label}",
	"resource.showTitle": "تفاصيل {label}",
	"message.added": "تمت إضافة {label} بنجاح.",
	"message.changed": "تم تعديل {label} بنجاح.",
	"message.deleted": "تم حذف {label} بنجاح.",
	"message.deletedCount": "تم حذف {count} من {label} بنجاح.",
	"delete.confirm": "هل أنت متأكد أنك تريد حذف هذا {label}؟",
	"delete.confirmSelected": "هل أنت متأكد أنك تريد حذف {label} المحددة؟",
	"delete.yes": "نعم، أنا متأكد",
	"delete.cancel": "لا، عد بي",
	"settings.flags": "أعلام الميزات",
	"settings.flagsEmpty": "لا توجد أعلام للعرض.",
	"settings.enabled": "مُفعّل",
	"settings.disabled": "مُعطّل",
	"settings.enable": "تفعيل",
	"settings.disable": "تعطيل",
	"settings.maintenance": "وضع الصيانة",
	"settings.current": "الحالي:",
	"settings.maintOn": "قيد الصيانة",
	"settings.maintOff": "تعمل بشكل طبيعي",
	"settings.maintEnable": "بدء الصيانة",
	"settings.maintDisable": "إنهاء الصيانة",
	"dateHierarchy.all": "كل التواريخ",
	"auth.logIn": "تسجيل الدخول",
	"auth.logOut": "تسجيل الخروج",
	"auth.username": "اسم المستخدم",
	"auth.password": "كلمة المرور",
	"auth.invalid": "يرجى إدخال اسم مستخدم وكلمة مرور صحيحين.",
} satisfies AdminCatalog;

/**
 * The admin panel's catalog bundle. `en` is the default/fallback; `ja`, `zh`, `es`,
 * `fr`, `de`, `pt`, `ru`, `ko`, and `ar` are matched against `c.get("language")`
 * (two-letter base codes, to maximize matches from `languageDetector`).
 */
export const adminCatalogBundle: CatalogBundle<AdminCatalog> = {
	en,
	ja,
	zh,
	es,
	fr,
	de,
	pt,
	ru,
	ko,
	ar,
};

/** The admin panel's translator, falling back to `en` when the detected language isn't in the bundle. */
export const adminTranslator = new Translator(adminCatalogBundle, { fallbackLanguage: "en" });

/**
 * The type of the bound translation function views receive as the `t` prop:
 * `Context` is already captured, so callers only pass `key` (and optional
 * interpolation `params`).
 */
export type AdminT = (key: keyof AdminCatalog, params?: TranslateParams) => string;

/** Builds an `AdminT` bound to `c`, so admin views can call `t(key)` without threading `Context` through. */
export const bindAdminT =
	(c: Context): AdminT =>
	(key, params) =>
		adminTranslator.t(c, key, params);
