/**
 * Zero-dependency OAuth 2.0 client (Authorization Code + PKCE, RFC 6749 / RFC 7636).
 *
 * Implemented using only WebCrypto (`crypto.subtle`, `crypto.getRandomValues`)
 * and `fetch`, adding no external library to the core. Following the precedent
 * of not placing vendor-specific implementations in the core (backend
 * agnosticism), provider-specific presets (endpoint constants for
 * Google/GitHub etc.) are not bundled. Callers pass endpoints directly via
 * `OAuthClientOptions`.
 *
 * @example
 * ```ts
 * // Google
 * const google = new OAuthClient({
 *   authorizationEndpoint: "https://accounts.google.com/o/oauth2/v2/auth",
 *   tokenEndpoint: "https://oauth2.googleapis.com/token",
 *   userInfoEndpoint: "https://openidconnect.googleapis.com/v1/userinfo",
 *   clientId: env.GOOGLE_CLIENT_ID,
 *   clientSecret: env.GOOGLE_CLIENT_SECRET,
 * });
 *
 * // GitHub
 * const github = new OAuthClient({
 *   authorizationEndpoint: "https://github.com/login/oauth/authorize",
 *   tokenEndpoint: "https://github.com/login/oauth/access_token",
 *   userInfoEndpoint: "https://api.github.com/user",
 *   clientId: env.GITHUB_CLIENT_ID,
 *   clientSecret: env.GITHUB_CLIENT_SECRET,
 * });
 * ```
 *
 * Storing `state`/`codeVerifier` in the session and finding-or-creating the
 * user are the application's responsibility. This class only handles the
 * protocol portion (building the authorization URL, exchanging the code,
 * refreshing, fetching user info).
 */
import { decodeBase64Url, encodeBase64Url } from "../support/base64url.js";
import { timeoutSignal } from "../support/fetch_timeout.js";

export type OAuthClientOptions = {
	/** Authorization endpoint (e.g. `https://accounts.google.com/o/oauth2/v2/auth`). Pass the URL without a query string. */
	authorizationEndpoint: string;
	/** Token endpoint. */
	tokenEndpoint: string;
	clientId: string;
	/** Only set this for a confidential client. Sent in the token request body. */
	clientSecret?: string;
	/** User info endpoint (used by `fetchUserInfo`). Calling `fetchUserInfo` without this set throws. */
	userInfoEndpoint?: string;
	/** For test injection. Defaults to the global `fetch`. */
	fetch?: typeof fetch;
	/**
	 * Timeout (in milliseconds) for requests to the token endpoint and the user
	 * info endpoint. No timeout by default (matching prior behavior). Since
	 * Cloudflare Workers' `fetch` has no default timeout, specifying this is
	 * recommended in production.
	 */
	timeoutMs?: number;
};

export type OAuthTokens = {
	accessToken: string;
	tokenType: string;
	expiresIn?: number;
	refreshToken?: string;
	scope?: string;
	idToken?: string;
	/** The raw response from the token endpoint (for referencing extension fields not covered above). */
	raw: Record<string, unknown>;
};

export type AuthorizationUrlOptions = {
	redirectUri: string;
	state: string;
	scopes?: string[];
	/** The PKCE code challenge (generated by `codeChallengeS256`). When set, `code_challenge_method=S256` is added. */
	codeChallenge?: string;
	/** Provider-specific extra parameters such as `access_type=offline` or `prompt`. */
	extraParams?: Record<string, string>;
};

export type ExchangeCodeOptions = {
	code: string;
	redirectUri: string;
	/** The PKCE verifier used for validation (generated by `generateCodeVerifier`). */
	codeVerifier?: string;
};

/** An error raised at the OAuth 2.0 token endpoint or user info endpoint. */
export class OAuthError extends Error {
	/** The RFC 6749 error code (e.g. `invalid_grant`). HTTP-level errors use `"http_error"`. */
	readonly error: string;
	readonly errorDescription?: string;
	/** The HTTP status code of the response. */
	readonly status?: number;

	constructor(error: string, errorDescription?: string, status?: number) {
		super(errorDescription ? `${error}: ${errorDescription}` : error);
		this.name = "OAuthError";
		this.error = error;
		this.errorDescription = errorDescription;
		this.status = status;
	}
}

/** Reads the response body as JSON, returning an empty object on failure (for error responses with an empty or non-JSON body). */
const parseJsonBody = async (response: Response): Promise<Record<string, unknown>> => {
	try {
		const parsed: unknown = await response.json();
		return isRecord(parsed) ? parsed : {};
	} catch {
		return {};
	}
};

/** A type guard narrowing a value to a plain object (`Record<string, unknown>`). */
const isRecord = (value: unknown): value is Record<string, unknown> =>
	typeof value === "object" && value !== null;

/** Safely extracts a string field. Returns `undefined` if the value is missing or not a string. */
const stringField = (body: Record<string, unknown>, key: string): string | undefined => {
	const value = body[key];
	return typeof value === "string" ? value : undefined;
};

/** Safely extracts a numeric field. */
const numberField = (body: Record<string, unknown>, key: string): number | undefined => {
	const value = body[key];
	return typeof value === "number" ? value : undefined;
};

/**
 * Validates the token endpoint's response (a `Response`) and repackages it as
 * `OAuthTokens`. Throws `OAuthError` for a non-2xx status, or JSON containing
 * an `error` field.
 */
const parseTokenResponse = async (response: Response): Promise<OAuthTokens> => {
	const body = await parseJsonBody(response);
	const errorCode = stringField(body, "error");

	if (!response.ok || errorCode) {
		throw new OAuthError(
			errorCode ?? "http_error",
			stringField(body, "error_description"),
			response.ok ? undefined : response.status,
		);
	}

	const accessToken = stringField(body, "access_token");
	const tokenType = stringField(body, "token_type");
	if (accessToken === undefined || tokenType === undefined) {
		throw new OAuthError(
			"invalid_response",
			"The token endpoint response is missing access_token or token_type",
		);
	}

	return {
		accessToken,
		tokenType,
		expiresIn: numberField(body, "expires_in"),
		refreshToken: stringField(body, "refresh_token"),
		scope: stringField(body, "scope"),
		idToken: stringField(body, "id_token"),
		raw: body,
	};
};

/**
 * A general-purpose OAuth 2.0 client (Authorization Code + PKCE). All methods
 * are arrow-function class fields because they may be passed by reference
 * from handlers.
 */
export class OAuthClient {
	private readonly options: OAuthClientOptions;
	private readonly fetch: typeof fetch;

	constructor(options: OAuthClientOptions) {
		this.options = options;
		this.fetch = options.fetch ?? fetch;
	}

	/**
	 * Builds the URL to redirect the user to for the authorization endpoint.
	 * `scopes` is space-joined into the `scope` parameter; when `codeChallenge`
	 * is given, PKCE's `code_challenge` and `code_challenge_method=S256` are added.
	 */
	readonly authorizationUrl = (options: AuthorizationUrlOptions): string => {
		const params = new URLSearchParams({
			response_type: "code",
			client_id: this.options.clientId,
			redirect_uri: options.redirectUri,
			state: options.state,
		});

		if (options.scopes && options.scopes.length > 0) {
			params.set("scope", options.scopes.join(" "));
		}
		if (options.codeChallenge) {
			params.set("code_challenge", options.codeChallenge);
			params.set("code_challenge_method", "S256");
		}
		if (options.extraParams) {
			for (const [key, value] of Object.entries(options.extraParams)) {
				params.set(key, value);
			}
		}

		return `${this.options.authorizationEndpoint}?${params.toString()}`;
	};

	/**
	 * Exchanges an authorization code for an access token. `client_secret` (when
	 * configured) is sent in the body rather than via Basic auth. This is the
	 * most compatible approach, including for providers that don't implement
	 * Basic auth. `Accept: application/json` is set because GitHub returns
	 * `application/x-www-form-urlencoded` responses if it's omitted.
	 */
	readonly exchangeCode = async (options: ExchangeCodeOptions): Promise<OAuthTokens> => {
		const params = new URLSearchParams({
			grant_type: "authorization_code",
			code: options.code,
			redirect_uri: options.redirectUri,
			client_id: this.options.clientId,
		});
		if (this.options.clientSecret !== undefined) {
			params.set("client_secret", this.options.clientSecret);
		}
		if (options.codeVerifier !== undefined) {
			params.set("code_verifier", options.codeVerifier);
		}

		return this.requestToken(params);
	};

	/** Obtains a new access token using a refresh token. Error handling is shared with `exchangeCode`. */
	readonly refresh = async (refreshToken: string): Promise<OAuthTokens> => {
		const params = new URLSearchParams({
			grant_type: "refresh_token",
			refresh_token: refreshToken,
			client_id: this.options.clientId,
		});
		if (this.options.clientSecret !== undefined) {
			params.set("client_secret", this.options.clientSecret);
		}

		return this.requestToken(params);
	};

	/** Shared request logic for the token endpoint. */
	private readonly requestToken = async (params: URLSearchParams): Promise<OAuthTokens> => {
		const response = await this.fetch(this.options.tokenEndpoint, {
			method: "POST",
			headers: {
				"content-type": "application/x-www-form-urlencoded",
				accept: "application/json",
			},
			body: params.toString(),
			signal: timeoutSignal(this.options.timeoutMs),
		});

		return parseTokenResponse(response);
	};

	/** Fetches user info from the user info endpoint using an access token. */
	readonly fetchUserInfo = async (accessToken: string): Promise<Record<string, unknown>> => {
		if (!this.options.userInfoEndpoint) {
			throw new Error(
				"OAuthClient has no userInfoEndpoint configured, so fetchUserInfo cannot be called",
			);
		}

		const response = await this.fetch(this.options.userInfoEndpoint, {
			headers: {
				authorization: `Bearer ${accessToken}`,
				accept: "application/json",
			},
			signal: timeoutSignal(this.options.timeoutMs),
		});

		if (!response.ok) {
			const body = await parseJsonBody(response);
			throw new OAuthError(
				stringField(body, "error") ?? "http_error",
				stringField(body, "error_description"),
				response.status,
			);
		}

		return parseJsonBody(response);
	};
}

/** Generates `length` bytes of randomness via `crypto.getRandomValues`. */
const randomBytes = (length: number): Uint8Array => crypto.getRandomValues(new Uint8Array(length));

/** Generates the CSRF-protection state parameter (base64url of 32 random bytes, 43 characters). */
export const generateState = (): string => encodeBase64Url(randomBytes(32));

/** Generates a PKCE code verifier (RFC 7636; base64url of 32 random bytes, 43 characters). */
export const generateCodeVerifier = (): string => encodeBase64Url(randomBytes(32));

/** Derives an S256 code challenge from a PKCE code verifier (RFC 7636 §4.2). */
export const codeChallengeS256 = async (verifier: string): Promise<string> => {
	const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(verifier));
	return encodeBase64Url(new Uint8Array(digest));
};

/**
 * Decodes the payload portion of an ID Token (JWT) and returns it as JSON.
 * **Signature verification is not performed**, so this is only intended for
 * use with an ID Token received directly from the token endpoint over TLS
 * (this function cannot be used to verify a token received via a third party).
 */
export const decodeIdToken = (idToken: string): Record<string, unknown> => {
	const parts = idToken.split(".");
	if (parts.length !== 3) {
		throw new Error(
			"The token passed to decodeIdToken has an invalid format (a JWT requires 3 parts)",
		);
	}

	let json: string;
	try {
		json = new TextDecoder().decode(decodeBase64Url(parts[1]));
	} catch {
		throw new Error("The payload of the token passed to decodeIdToken is not valid base64url");
	}

	let parsed: unknown;
	try {
		parsed = JSON.parse(json);
	} catch {
		throw new Error("The payload of the token passed to decodeIdToken is not valid JSON");
	}

	if (!isRecord(parsed)) {
		throw new Error("The payload of the token passed to decodeIdToken is not an object");
	}
	return parsed;
};
